obj-$(CONFIG_CAMERA_APERTURE_AK7372_OBJ) += is-aperture-ak7372.o

ccflags-y := -Idrivers/media/platform/exynos/camera
ccflags-y += -Idrivers/media/platform/exynos/camera/include
ccflags-y += -Idrivers/media/platform/exynos/camera/vendor
ccflags-y += -Idrivers/media/platform/exynos/camera/hardware/api
ccflags-y += -Idrivers/media/platform/exynos/camera/sensor
ccflags-y += -Idrivers/media/platform/exynos/camera/sensor/module_framework
