# drivers/samsung/perf/Makefile
#
# Copyright (c) 2010-2019 Samsung Electronics Co., Ltd.
#		http://www.samsung.com/
#
# Licensed under GPLv2
#

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

ccflags-y := -Wformat

obj-$(CONFIG_SEC_PERF_LATENCYCHECKER)   += sec_perf_latencychecker.o
obj-$(CONFIG_SEC_BOOTSTAT)	+= sec_bootstat.o
