# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel panel device drivers.
#

obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HAC) += s6e3hac.o
obj-$(CONFIG_EXTEND_LIVE_CLOCK) += s6e3hac_aod.o
obj-$(CONFIG_SUPPORT_DISPLAY_PROFILER) += s6e3hac_profiler.o
