obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX) += abox_util.o abox_dbg.o abox_dump.o \
	abox_log.o abox_gic.o abox.o abox_soc.o abox_core.o abox_rdma.o \
	abox_wdma.o abox_if.o abox_effect.o abox_vss.o abox_failsafe.o \
	abox_vdma.o abox_msg.o abox_ipc.o abox_qos.o abox_ion.o \
	abox_cmpnt.o abox_tplg.o abox_dma.o abox_pci.o abox_shm.o
obj-$(CONFIG_SEC_SND_ADAPTATION) += abox_adaptation.o

GCOV_PROFILE_abox.o	:=y
GCOV_PROFILE_abox_shm.o	:=y
GCOV_PROFILE_abox_cmpnt.o	:=y