obj-$(CONFIG_CAMERA_FLASH_LM3560_OBJ) += is-flash-lm3560.o
obj-$(CONFIG_CAMERA_FLASH_RT5033_OBJ) += is-flash-rt5033.o
obj-$(CONFIG_CAMERA_FLASH_S2MPB02_OBJ) += is-flash-s2mpb02.o
obj-$(CONFIG_CAMERA_FLASH_S2MU106_OBJ) += is-flash-s2mu106.o
obj-$(CONFIG_CAMERA_FLASH_GPIO_OBJ) += is-flash-gpio.o
obj-$(CONFIG_CAMERA_FLASH_KTD2692_OBJ) += is-flash-ktd2692.o
obj-$(CONFIG_CAMERA_FLASH_S2MU107_OBJ) += is-flash-s2mu107.o
obj-$(CONFIG_CAMERA_FLASH_RT8547_OBJ) += is-flash-rt8547.o
obj-$(CONFIG_CAMERA_FLASH_I2C_OBJ) += is-helper-flash-i2c.o \
				      is-flash-i2c.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor
