obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += is-hw-control.o \
		is-hw-3aa.o \
		is-hw-isp.o \
		is-hw-vra.o \
		is-hw-dm.o \
		is-hw-tdnr-v2.o	\
		is-hw-clahe.o

obj-$(CONFIG_PABLO_V7_0_0) += is-hw-mcscaler-v2.o \
		is-hw-djag.o \
		is-hw-uvsp-cac.o
obj-$(CONFIG_PABLO_V8_0_0) += is-hw-mcscaler-v3.o \
		is-hw-djag-v2.o \
		is-hw-cac.o
obj-$(CONFIG_PABLO_V8_1_0) += is-hw-mcscaler-v3.o \
		is-hw-djag-v2.o \
		is-hw-cac.o
obj-$(CONFIG_PABLO_V8_10_0) += is-hw-mcscaler-v3.o \
		is-hw-djag-v2.o \
		is-hw-cac.o

obj-$(CONFIG_PABLO_V8_20_0) += is-hw-mcscaler-v3.o \
		is-hw-djag-v2.o \
		is-hw-cac.o

obj-$(CONFIG_CAMERA_PDP) += is-hw-pdp.o

obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += api/

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/interface
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
