#
# Makefile for the dsp driver depends on exynos9830
#

ccflags-y += -Idrivers/vision/dsp
ccflags-y += -Idrivers/vision/dsp/hardware/exynos$(CONFIG_EXYNOS_SOC_NAME)

obj-y	+= dsp-hw-system.o
obj-y	+= dsp-hw-pm.o
obj-y	+= dsp-hw-clk.o
obj-y	+= dsp-hw-bus.o
obj-y	+= dsp-hw-interface.o
obj-y	+= dsp-hw-debug.o
obj-y	+= dsp-hw-ctrl.o
obj-y	+= dsp-hw-memory.o
obj-y	+= dsp-hw-mailbox.o
obj-y	+= dsp-hw-dump.o
