
enum acpm_dvfs_id {
	MIF = ACPM_VCLK_TYPE,
	INT,
	CPUCL0,
	CPUCL1,
	CPUCL2,
	NPU,
	DISP,
	DSP,
	AUD,
	CP,
	G3D,
	INTCAM,
	CAM,
	TNR,
	DNC,
	MFC,
};

struct vclk acpm_vclk_list[] = {
	CMUCAL_ACPM_VCLK(MIF, NULL, NULL, NULL, NULL, MARGIN_MIF),
	CMUCAL_ACPM_VCLK(INT, NULL, NULL, NULL, NULL, MARGIN_INT),
	CMUCAL_ACPM_VCLK(CPUCL0, NULL, NULL, NULL, NULL, MARGIN_LIT),
	CMUCAL_ACPM_VCLK(CPUCL1, NULL, NULL, NULL, NULL, MARGIN_MID),
	CMUCAL_ACPM_VCLK(CPUCL2, NULL, NULL, NULL, NULL, MARGIN_BIG),
	CMUCAL_ACPM_VCLK(NPU, NULL, NULL, NULL, NULL, MARGIN_NPU),
	CMUCAL_ACPM_VCLK(DISP, NULL, NULL, NULL, NULL, MARGIN_DISP),
	CMUCAL_ACPM_VCLK(DSP, NULL, NULL, NULL, NULL, MARGIN_DSP),
	CMUCAL_ACPM_VCLK(AUD, NULL, NULL, NULL, NULL, MARGIN_AUD),
	CMUCAL_ACPM_VCLK(CP, NULL, NULL, NULL, NULL, MARGIN_CP),
	CMUCAL_ACPM_VCLK(G3D, NULL, NULL, NULL, NULL, MARGIN_G3D),
	CMUCAL_ACPM_VCLK(INTCAM, NULL, NULL, NULL, NULL, MARGIN_INTCAM),
	CMUCAL_ACPM_VCLK(CAM, NULL, NULL, NULL, NULL, MARGIN_CAM),
	CMUCAL_ACPM_VCLK(TNR, NULL, NULL, NULL, NULL, MARGIN_TNR),
	CMUCAL_ACPM_VCLK(DNC, NULL, NULL, NULL, NULL, MARGIN_DNC),
	CMUCAL_ACPM_VCLK(MFC, NULL, NULL, NULL, NULL, MARGIN_MFC),
};

unsigned int acpm_vclk_size = ARRAY_SIZE(acpm_vclk_list);
