obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += is-interface-ischain.o \
		is-interface-library.o \
		is-interface-vra.o \
		is-interface-ddk.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
