obj-y += core.o energy.o multi_load.o ontime.o load_balance.o
obj-y += sparing.o
obj-y += cpu_select.o energy_select.o
obj-$(CONFIG_CPU_FREQ_GOV_ENERGYSTEP) += energy_step.o
obj-$(CONFIG_SCHED_USE_FLUID_RT) += frt.o
obj-$(CONFIG_SCHED_EMS_TUNE) += tune.o
obj-$(CONFIG_SCHED_PMU_CONT) += pmu_cont.o
