obj-$(CONFIG_CAMERA_OIS_SELECT) += is-helper-ois-i2c.o \
				is-ois.o

obj-$(CONFIG_CAMERA_OIS_IDG2030_OBJ) += is-ois-idg2030.o
obj-$(CONFIG_CAMERA_OIS_BU24218GWL_OBJ) += is-ois-bu24218gwl.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/sensor
