obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP)	+= is-interface-sensor.o \
				       is-interface-actuator.o \
				       is-control-sensor.o \
				       is-control-actuator.o \
				       is-device-sensor-peri.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
