obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += is-hw-api-common.o \
		is-hw-api-vra.o

obj-$(CONFIG_MC_SCALER_V5_0) += is-hw-api-mcscaler-v5_0.o
obj-$(CONFIG_MC_SCALER_V8_0) += is-hw-api-mcscaler-v8_0.o
obj-$(CONFIG_MC_SCALER_V8_1) += is-hw-api-mcscaler-v8_1.o
obj-$(CONFIG_MC_SCALER_V8_10) += is-hw-api-mcscaler-v8_10.o
obj-$(CONFIG_MC_SCALER_V8_20) += is-hw-api-mcscaler-v8_20-v8_21.o

obj-$(CONFIG_PDP_V1_0) += is-hw-api-pdp-v1_0.o
obj-$(CONFIG_PDP_V1_0_0) += is-hw-api-pdp-v1_0_0.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
