obj-$(CONFIG_CAMERA_EEPROM_SELECT) += is-sensor-eeprom.o
obj-$(CONFIG_CAMERA_EEPROM_GM1_OBJ) += is-sensor-eeprom-gm1.o
obj-$(CONFIG_CAMERA_EEPROM_5E9_OBJ) += is-sensor-eeprom-5e9.o

ccflags-y := -Idrivers/media/platform/exynos/camera
ccflags-y += -Idrivers/media/platform/exynos/camera/include
ccflags-y += -Idrivers/media/platform/exynos/camera/vendor
ccflags-y += -Idrivers/media/platform/exynos/camera/hardware/api
ccflags-y += -Idrivers/media/platform/exynos/camera/sensor
ccflags-y += -Idrivers/media/platform/exynos/camera/sensor/module_framework
