obj-$(CONFIG_SND_SOC_SAMSUNG_MAILBOX) += mailbox.o
obj-$(CONFIG_SND_SOC_SAMSUNG_VTS) += vts.o \
				     vts_log.o \
				     vts_dump.o \
				     vts_dbg.o \
				     vts_dma.o \
				     vts_proc.o
obj-$(CONFIG_SND_SOC_SAMSUNG_VTS_S_LIF) += vts_util.o \
					   vts_s_lif_clk_table.o \
					   vts_s_lif_nm.o \
					   vts_s_lif_soc.o \
					   vts_s_lif_dump.o \
					   vts_s_lif.o
