/* sound/soc/samsung/vts/vts_s_lif.h
 *
 * ALSA SoC - Samsung VTS Serial Local Interface driver
 *
 * Copyright (c) 2019 Samsung Electronics Co. Ltd.
  *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __SND_SOC_VTS_S_LIF_H
#define __SND_SOC_VTS_S_LIF_H

#include <sound/memalloc.h>
#include <linux/wakelock.h>

#define GENMASK32(h, l) \
	(((~0U) - (1U << (l)) + 1) & (~0U >> (32 - 1 - (h))))
#define VTS_S_SOC_VERSION(m, n, r) (((m) << 16) | ((n) << 8) | (r))
#define VTS_S_FLD(name) (GENMASK32(VTS_S_##name##_H, \
			VTS_S_##name##_L))
#define VTS_S_SFR(name, o, x) (VTS_S_##name##_BASE + \
				((x) * VTS_S_##name##_ITV) + (o))
#define VTS_S_BMASK(name, x) (VTS_S_##name##_MASK_BIT << \
				((x) * VTS_S_##name##_ITV))

#define VTS_S_LIF_MAX_CHANNEL			(8)

#define VTS_S_LIF_MAX_REGISTER			(0x328)
#define VTS_S_LIF_DMIC_AUD_MAX_REGISTER		(0x10)

/* 1. SERIAL LIF register base */
#define VTS_S_SFR_APB_BASE			(0x30)
#define VTS_S_INT_EN_SET_BASE			(0x40)
#define VTS_S_INT_EN_CLR_BASE			(0x44)
#define VTS_S_INT_PEND_BASE			(0x48)
#define VTS_S_INT_CLR_BASE			(0x4C)

#define VTS_S_CTRL_BASE				(0x100)

#define VTS_S_CONFIG_MASTER_BASE		(0x104)
#define VTS_S_CONFIG_SLAVE_BASE			(0x108)

#define VTS_S_CONFIG_DONE_BASE			(0x10C)

#define VTS_S_SAMPLE_PCNT_BASE			(0x110)
#define VTS_S_INPUT_EN_BASE			(0x114)

#define VTS_S_VOL_SET_BASE			(0x118)
#define VTS_S_VOL_SET_ITV			(0x4)
#define VTS_S_VOL_SET(x)			VTS_S_SFR(VOL_SET, 0x0, x)

#define VTS_S_VOL_CHANGE_BASE			(0x128)
#define VTS_S_VOL_CHANGE_ITV			(0x4)
#define VTS_S_VOL_CHANGE(x)			VTS_S_SFR(VOL_CHANGE, 0x0, x)

#define VTS_S_CHANNEL_MAP_BASE			(0x138)
#define VTS_S_CHANNEL_MAP_ITV			(0x4)

#define VTS_S_DBG_INFO0_BASE			(0x150)
#define VTS_S_DBG_INOF1_BASE			(0x154)

#define VTS_S_MSIF_FIFO00_BASE			(0x200)
#define VTS_S_MSIF_FIFO01_BASE			(0x204)
#define VTS_S_MSIF_FIFO10_BASE			(0x208)
#define VTS_S_MSIF_FIFO11_BASE			(0x20C)

#define VTS_S_MSIF_FIFO20_BASE			(0x210)
#define VTS_S_MSIF_FIFO21_BASE			(0x214)
#define VTS_S_MSIF_FIFO30_BASE			(0x218)
#define VTS_S_MSIF_FIFO31_BASE			(0x21C)

#define VTS_S_SSIF_FIFO00_BASE			(0x200)
#define VTS_S_SSIF_FIFO01_BASE			(0x204)
#define VTS_S_SSIF_FIFO10_BASE			(0x208)
#define VTS_S_SSIF_FIFO11_BASE			(0x20C)

#define VTS_S_SSIF_FIFO20_BASE			(0x210)
#define VTS_S_SSIF_FIFO21_BASE			(0x214)
#define VTS_S_SSIF_FIFO30_BASE			(0x218)
#define VTS_S_SSIF_FIFO31_BASE			(0x21C)

#define VTS_S_CONTROL_AHB_WMASTER_BASE		(0x300)

#define VTS_S_STARTADDR_SET0_BASE		(0x304)
#define VTS_S_ENDADDR_SET0_BASE			(0x308)
#define VTS_S_FILLED_SIZE_SET0_BASE		(0x30C)
#define VTS_S_WRITE_POINTER_SET0_BASE		(0x310)
#define VTS_S_READ_POINTER_SET0_BASE		(0x314)

#define VTS_S_STARTADDR_SET1_BASE		(0x318)
#define VTS_S_ENDADDR_SET1_BASE			(0x31C)
#define VTS_S_FILLED_SIZE_SET1_BASE		(0x320)
#define VTS_S_WRITE_POINTER_SET1_BASE		(0x324)
#define VTS_S_READ_POINTER_SET1_BASE		(0x328)


/* SYS REG : 0x15510000 + 1010 */
#define VTS_S_SEL_PAD_AUD_BASE			(0x0) /* 0x15511010 */
#define VTS_S_SEL_DIV2_CLK_BASE			(0x4) /* 0x15511014 */

/* INT_EN_SET */
/* INT_EN_CLR */
/* INT_PEND */
/* INT_CLR */
/* VTS_S_LIF_CTRL_BASE */
#define VTS_S_CTRL_MASTER_IF_EN_H		(0)
#define VTS_S_CTRL_MASTER_IF_EN_L		(0)
#define VTS_S_CTRL_MASTER_IF_EN_MASK		VTS_S_FLD(CTRL_MASTER_IF_EN)
#define VTS_S_CTRL_SLAVE_IF_EN_H		(4)
#define VTS_S_CTRL_SLAVE_IF_EN_L		(4)
#define VTS_S_CTRL_SLAVE_IF_EN_MASK		VTS_S_FLD(CTRL_SLAVE_IF_EN)
#define VTS_S_CTRL_SPU_EN_H			(8)
#define VTS_S_CTRL_SPU_EN_L			(8)
#define VTS_S_CTRL_SPU_EN_MASK			VTS_S_FLD(CTRL_SPU_EN)
#define VTS_S_CTRL_LOOPBACK_EN_H		(12)
#define VTS_S_CTRL_LOOPBACK_EN_L		(12)
#define VTS_S_CTRL_LOOPBACK_EN_MASK		VTS_S_FLD(CTRL_LOOPBACK_EN)

/* CONFIG_MASTER */
#if (VTS_S_SOC_VERSION(1, 0, 0) == CONFIG_SND_SOC_SAMSUNG_VTS_S_LIF_VERSION)
#define VTS_S_CONFIG_MASTER_OPMODE_H		(3)
#define VTS_S_CONFIG_MASTER_OPMODE_L		(0)
#define VTS_S_CONFIG_MASTER_OPMODE_MASK		VTS_S_FLD(CONFIG_MASTER_OPMODE)
#elif (VTS_S_SOC_VERSION(1, 1, 1) >= CONFIG_SND_SOC_SAMSUNG_VTS_S_LIF_VERSION)
#define VTS_S_CONFIG_MASTER_OP_D_H		(3)
#define VTS_S_CONFIG_MASTER_OP_D_L		(3)
#define VTS_S_CONFIG_MASTER_OP_D_MASK		VTS_S_FLD(CONFIG_MASTER_OP_D)
#define VTS_S_CONFIG_MASTER_OP_C_H		(2)
#define VTS_S_CONFIG_MASTER_OP_C_L		(0)
#define VTS_S_CONFIG_MASTER_OP_C_MASK		VTS_S_FLD(CONFIG_MASTER_OP_C)
#else
#error "VTS_S_SOC_VERSION is not defined"
#endif
#define VTS_S_CONFIG_MASTER_WS_MODE_H		(4)
#define VTS_S_CONFIG_MASTER_WS_MODE_L		(4)
#define VTS_S_CONFIG_MASTER_WS_MODE_MASK	VTS_S_FLD(CONFIG_MASTER_WS_MODE)
#define VTS_S_CONFIG_MASTER_WS_POLAR_H		(8)
#define VTS_S_CONFIG_MASTER_WS_POLAR_L		(8)
#define VTS_S_CONFIG_MASTER_WS_POLAR_MASK	VTS_S_FLD(CONFIG_MASTER_WS_POLAR)
#define VTS_S_CONFIG_MASTER_DIFF_MSIF_STR_H	(15)
#define VTS_S_CONFIG_MASTER_DIFF_MSIF_STR_L	(12)
#define VTS_S_CONFIG_MASTER_DIFF_MSIF_STR_MASK	VTS_S_FLD(CONFIG_MASTER_DIFF_MSIF_STR)

/* CONFIG_SLAVE */
#if (VTS_S_SOC_VERSION(1, 0, 0) == CONFIG_SND_SOC_SAMSUNG_VTS_S_LIF_VERSION)
#define VTS_S_CONFIG_SLAVE_OPMODE_H		(3)
#define VTS_S_CONFIG_SLAVE_OPMODE_L		(0)
#define VTS_S_CONFIG_SLAVE_OPMODE_MASK		VTS_S_FLD(CONFIG_SLAVE_OPMODE)
#elif (VTS_S_SOC_VERSION(1, 1, 1) >= CONFIG_SND_SOC_SAMSUNG_VTS_S_LIF_VERSION)
#define VTS_S_CONFIG_SLAVE_OP_D_H		(3)
#define VTS_S_CONFIG_SLAVE_OP_D_L		(3)
#define VTS_S_CONFIG_SLAVE_OP_D_MASK		VTS_S_FLD(CONFIG_SLAVE_OP_D)
#define VTS_S_CONFIG_SLAVE_OP_C_H		(2)
#define VTS_S_CONFIG_SLAVE_OP_C_L		(0)
#define VTS_S_CONFIG_SLAVE_OP_C_MASK		VTS_S_FLD(CONFIG_SLAVE_OP_C)
#else
#error "VTS_S_SOC_VERSION is not defined"
#endif
#define VTS_S_CONFIG_SLAVE_WS_MODE_H		(4)
#define VTS_S_CONFIG_SLAVE_WS_MODE_L		(4)
#define VTS_S_CONFIG_SLAVE_WS_MODE_MASK		VTS_S_FLD(CONFIG_SLAVE_WS_MODE)
#define VTS_S_CONFIG_SLAVE_WS_POLAR_H		(8)
#define VTS_S_CONFIG_SLAVE_WS_POLAR_L		(8)
#define VTS_S_CONFIG_SLAVE_WS_POLAR_MASK	VTS_S_FLD(CONFIG_SLAVE_WS_POLAR)
#define VTS_S_CONFIG_SLAVE_DIFF_MSIF_STR_H	(15)
#define VTS_S_CONFIG_SLAVE_DIFF_MSIF_STR_L	(12)
#define VTS_S_CONFIG_SLAVE_DIFF_MSIF_STR_MASK	VTS_S_FLD(CONFIG_SLAVE_DIFF_MSIF_STR)
#define VTS_S_CONFIG_SLAVE_BCLK_SEL_H		(16)
#define VTS_S_CONFIG_SLAVE_BCLK_SEL_L		(16)
#define VTS_S_CONFIG_SLAVE_BCLK_SEL_MASK	VTS_S_FLD(CONFIG_SLAVE_BCLK_SEL)

/* CONFIG_DONE */
#define VTS_S_CONFIG_DONE_ALL_CONFIG_H		(0)
#define VTS_S_CONFIG_DONE_ALL_CONFIG_L		(0)
#define VTS_S_CONFIG_DONE_ALL_CONFIG_MASK	VTS_S_FLD(CONFIG_DONE_ALL_CONFIG)
#define VTS_S_CONFIG_DONE_MASTER_CONFIG_H	(4)
#define VTS_S_CONFIG_DONE_MASTER_CONFIG_L	(4)
#define VTS_S_CONFIG_DONE_MASTER_CONFIG_MASK	VTS_S_FLD(CONFIG_DONE_MASTER_CONFIG)
#define VTS_S_CONFIG_DONE_SLAVE_CONFIG_H	(8)
#define VTS_S_CONFIG_DONE_SLAVE_CONFIG_L	(8)
#define VTS_S_CONFIG_DONE_SLAVE_CONFIG_MASK	VTS_S_FLD(CONFIG_DONE_SLAVE_CONFIG)

/* SAMPLE_PCNT */

/* INPUT_EN */
#define VTS_S_INPUT_EN_EN0_H			(0)
#define VTS_S_INPUT_EN_EN0_L			(0)
#define VTS_S_INPUT_EN_EN0_MASK			VTS_S_FLD(INPUT_EN_EN0)
#define VTS_S_INPUT_EN_EN1_H			(1)
#define VTS_S_INPUT_EN_EN1_L			(1)
#define VTS_S_INPUT_EN_EN1_MASK			VTS_S_FLD(INPUT_EN_EN1)
#define VTS_S_INPUT_EN_EN2_H			(2)
#define VTS_S_INPUT_EN_EN2_L			(2)
#define VTS_S_INPUT_EN_EN2_MASK			VTS_S_FLD(INPUT_EN_EN2)
#define VTS_S_INPUT_EN_EN3_H			(3)
#define VTS_S_INPUT_EN_EN3_L			(3)
#define VTS_S_INPUT_EN_EN3_MASK			VTS_S_FLD(INPUT_EN_EN3)
#define VTS_S_INPUT_EN_FADE_IN_EN0_H		(4)
#define VTS_S_INPUT_EN_FADE_IN_EN0_L		(4)
#define VTS_S_INPUT_EN_FADE_IN_EN0_MASK		VTS_S_FLD(INPUT_EN_FADE_IN_EN0)
#define VTS_S_INPUT_EN_FADE_IN_EN1_H		(5)
#define VTS_S_INPUT_EN_FADE_IN_EN1_L		(5)
#define VTS_S_INPUT_EN_FADE_IN_EN1_MASK		VTS_S_FLD(INPUT_EN_FADE_IN_EN1)
#define VTS_S_INPUT_EN_FADE_IN_EN2_H		(6)
#define VTS_S_INPUT_EN_FADE_IN_EN2_L		(6)
#define VTS_S_INPUT_EN_FADE_IN_EN2_MASK		VTS_S_FLD(INPUT_EN_FADE_IN_EN2)
#define VTS_S_INPUT_EN_FADE_IN_EN3_H		(7)
#define VTS_S_INPUT_EN_FADE_IN_EN3_L		(7)
#define VTS_S_INPUT_EN_FADE_IN_EN3_MASK		VTS_S_FLD(INPUT_EN_FADE_IN_EN3)
#define VTS_S_INPUT_EN_FADE_OUT_EN0_H		(8)
#define VTS_S_INPUT_EN_FADE_OUT_EN0_L		(8)
#define VTS_S_INPUT_EN_FADE_OUT_EN0_MASK	VTS_S_FLD(INPUT_EN_FADE_IN_EN0)
#define VTS_S_INPUT_EN_FADE_OUT_EN1_H		(9)
#define VTS_S_INPUT_EN_FADE_OUT_EN1_L		(9)
#define VTS_S_INPUT_EN_FADE_OUT_EN1_MASK	VTS_S_FLD(INPUT_EN_FADE_IN_EN1)
#define VTS_S_INPUT_EN_FADE_OUT_EN2_H		(10)
#define VTS_S_INPUT_EN_FADE_OUT_EN2_L		(10)
#define VTS_S_INPUT_EN_FADE_OUT_EN2_MASK	VTS_S_FLD(INPUT_EN_FADE_IN_EN2)
#define VTS_S_INPUT_EN_FADE_OUT_EN3_H		(11)
#define VTS_S_INPUT_EN_FADE_OUT_EN3_L		(11)
#define VTS_S_INPUT_EN_FADE_OUT_EN3_MASK	VTS_S_FLD(INPUT_EN_FADE_IN_EN3)

/* VOL_SET */
#define VTS_S_VOL_SET_H			(23)
#define VTS_S_VOL_SET_L			(0)
#define VTS_S_VOL_SET_MASK			VTS_S_FLD(VOL_SET)

/* VOL_change */
#define VTS_S_VOL_CHANGE_H			(23)
#define VTS_S_VOL_CHANGE_L			(0)
#define VTS_S_VOL_CHANGE_MASK			VTS_S_FLD(VOL_CHANGE)

/* CHANNEL_MAP */
#define VTS_S_CHANNEL_MAP_MASK_BIT		(0xF)
#define VTS_S_CHANNEL_MAP_MASK(x)		VTS_S_BMASK(CHANNEL_MAP, x)

/* DBG_INFO0 */
/* DBG_INFO1 */
/* MSIF_FIFO00 */
/* MSIF_FIFO01 */
/* MSIF_FIFO10 */
/* MSIF_FIFO11 */
/* MSIF_FIFO20 */
/* MSIF_FIFO21 */
/* MSIF_FIFO30 */
/* MSIF_FIFO31 */
/* SSIF_FIFO00 */
/* SSIF_FIFO01 */
/* SSIF_FIFO10 */
/* SSIF_FIFO11 */
/* SSIF_FIFO20 */
/* SSIF_FIFO21 */
/* SSIF_FIFO30 */
/* SSIF_FIFO31 */

/* CONTROL_AHB_WMASTER */
#define VTS_S_CONTROL_AHB_WMASTER_DIABLE_OVERFLOW_BUFFER_H	(0)
#define VTS_S_CONTROL_AHB_WMASTER_DIABLE_OVERFLOW_BUFFER_L	(0)
#define VTS_S_CONTROL_AHB_WMASTER_DIABLE_OVERFLOW_BUFFER_MASK	\
	VTS_S_FLD(CONTROL_AHB_WMASTER_DIABLE_OVERFLOW_BUFFER)
#define VTS_S_CONTROL_AHB_WMASTER_SETINFO_H			(4)
#define VTS_S_CONTROL_AHB_WMASTER_SETINFO_L			(4)
#define VTS_S_CONTROL_AHB_WMASTER_SETINFO_MASK	\
	VTS_S_FLD(CONTROL_AHB_WMASTER_SETINFO)
#define VTS_S_CONTROL_AHB_WMASTER_ENABLE_AHB_WMASTER_H		(8)
#define VTS_S_CONTROL_AHB_WMASTER_ENABLE_AHB_WMASTER_L		(8)
#define VTS_S_CONTROL_AHB_WMASTER_ENABLE_AHB_WMASTER_MASK	\
	VTS_S_FLD(CONTROL_AHB_WMASTER_ENABLE_AHB_WMASTER)

/* STARTADDR_SET0 */
#define VTS_S_STARTADDR_SET0_H			(31)
#define VTS_S_STARTADDR_SET0_L			(2)
#define VTS_S_STARTADDR_SET0_MASK		VTS_S_FLD(STARTADDR_SET0)
/* ENDADDR_SET0 */
#define VTS_S_ENDADDR_SET0_H			(31)
#define VTS_S_ENDADDR_SET0_L			(2)
#define VTS_S_ENDADDR_SET0_MASK			VTS_S_FLD(ENDADDR_SET0)
/* FILLED_SIZE_SET0 */
#define VTS_S_FILLED_SIZE_SET0_H		(31)
#define VTS_S_FILLED_SIZE_SET0_L		(2)
#define VTS_S_FILLED_SIZE_SET0_MASK		VTS_S_FLD(FILLED_SIZE_SET0)
/* WRITE_POINTER_SET0 */
#define VTS_S_WRITE_POINTER_SET0_H		(31)
#define VTS_S_WRITE_POINTER_SET0_L		(2)
#define VTS_S_WRITE_POINTER_SET0_MASK		VTS_S_FLD(WRITE_POINTER_SET0)
/* READ_POINTER_SET0 */
#define VTS_S_READ_POINTER_SET0_H		(31)
#define VTS_S_READ_POINTER_SET0_L		(2)
#define VTS_S_READ_POINTER_SET0_MASK		VTS_S_FLD(READ_POINTER_SET0)

/* STARTADDR_SET1 */
#define VTS_S_STARTADDR_SET1_H			(31)
#define VTS_S_STARTADDR_SET1_L			(2)
#define VTS_S_STARTADDR_SET1_MASK		VTS_S_FLD(STARTADDR_SET1)
/* ENDADDR_SET1 */
#define VTS_S_ENDADDR_SET1_H			(31)
#define VTS_S_ENDADDR_SET1_L			(2)
#define VTS_S_ENDADDR_SET1_MASK			VTS_S_FLD(ENDADDR_SET1)
/* FILLED_SIZE_SET1 */
#define VTS_S_FILLED_SIZE_SET1_H		(31)
#define VTS_S_FILLED_SIZE_SET1_L		(2)
#define VTS_S_FILLED_SIZE_SET1_MASK		VTS_S_FLD(FILLED_SIZE_SET1)
/* WRITE_POINTER_SET1 */
#define VTS_S_WRITE_POINTER_SET1_H		(31)
#define VTS_S_WRITE_POINTER_SET1_L		(2)
#define VTS_S_WRITE_POINTER_SET1_MASK		VTS_S_FLD(WRITE_POINTER_SET1)
/* READ_POINTER_SET1 */
#define VTS_S_READ_POINTER_SET1_H		(31)
#define VTS_S_READ_POINTER_SET1_L		(2)
#define VTS_S_READ_POINTER_SET1_MASK		VTS_S_FLD(READ_POINTER_SET1)

/* 2. DMIC AUD register base */
#define VTS_S_SFR_ENABLE_DMIC_AUD_BASE		(0x0)

#define VTS_S_SFR_CONTROL_DMIC_AUD_BASE		(0x4)
#define VTS_S_SFR_CONTROL_DMIC_AUD_HPF_SEL_H	(6)
#define VTS_S_SFR_CONTROL_DMIC_AUD_HPF_SEL_L	(1)
#define VTS_S_SFR_CONTROL_DMIC_AUD_HPF_SEL_MASK	\
	VTS_S_FLD(SFR_CONTROL_DMIC_AUD_HPF_SEL)
#define VTS_S_SFR_CONTROL_DMIC_AUD_SYS_SEL_H	(14)
#define VTS_S_SFR_CONTROL_DMIC_AUD_SYS_SEL_L	(12)
#define VTS_S_SFR_CONTROL_DMIC_AUD_SYS_SEL_MASK	\
	VTS_S_FLD(SFR_CONTROL_DMIC_AUD_SYS_SEL)
#define VTS_S_SFR_CONTROL_DMIC_AUD_GAIN_H	(26)
#define VTS_S_SFR_CONTROL_DMIC_AUD_GAIN_L	(21)
#define VTS_S_SFR_CONTROL_DMIC_AUD_GAIN_MASK	\
	VTS_S_FLD(SFR_CONTROL_DMIC_AUD_GAIN)
#define VTS_S_SFR_CONTROL_DMIC_AUD_HPF_EN_H	(31)
#define VTS_S_SFR_CONTROL_DMIC_AUD_HPF_EN_L	(31)
#define VTS_S_SFR_CONTROL_DMIC_AUD_HPF_EN_MASK	\
	VTS_S_FLD(SFR_CONTROL_DMIC_AUD_HPF_EN)

#define VTS_S_SFR_GAIN_MODE_BASE		(0x8)

#define VTS_S_SFR_MAX_SCALE_MODE_BASE		(0xC)

#define VTS_S_SFR_MAX_SCALE_GAIN_BASE		(0x10)

/* 3. DMIC AUD value */
#define VTS_S_LIF_DMIC_AUD_NUM			(3)
#define VTS_S_DEFAULT_GAIN_MODE			(0x1717)
#define VTS_S_DEFAULT_MAX_SCALE_GAIN		(0x85)
#define VTS_S_DEFAULT_CONTROL_DMIC_AUD		(0x8C63004C)

enum vts_s_lif_mode {
	VTS_S_MODE_SLAVE,
	VTS_S_MODE_MASTER,
	VTS_S_MODE_BOTH,
};

enum vts_s_lif_state {
	VTS_S_STATE_CLOSED,
	VTS_S_STATE_OPENED,
	VTS_S_STATE_SET_PARAM,
	VTS_S_STATE_DMA_ENBLED,
	VTS_S_STATE_DMA_DISABLED,
};

enum vts_s_lif_gain_mode {
	GAIN_MODE0,
	GAIN_MODE1,
	GAIN_MODE2,
};

enum vts_s_lif_max_scale_gain {
	MAX_SCALE_GAIN0,
	MAX_SCALE_GAIN1,
	MAX_SCALE_GAIN2,
};

enum vts_s_lif_control_dmic_aud {
	CONTROL_DMIC_AUD0,
	CONTROL_DMIC_AUD1,
	CONTROL_DMIC_AUD2,
};

enum vts_s_lif_vol_set {
	VOL_SET0,
	VOL_SET1,
	VOL_SET2,
	VOL_SET3,
};

enum s_lif_channel_map {
	MAP_CH0,
	MAP_CH1,
	MAP_CH2,
	MAP_CH3,
	MAP_CH4,
	MAP_CH5,
	MAP_CH6,
	MAP_CH7,
};

struct vts_s_lif_data {
	/* id */
	struct platform_device *pdev;
	struct device *dev;
	struct device *dev_vts;
	struct vts_data *vts_data;
	int id;
	char name[64];

	/* resouece */
	void __iomem *sfr_base;
	void __iomem *sfr_sys_base;
	void __iomem *sram_base;
	void __iomem *dmic_aud[VTS_S_LIF_DMIC_AUD_NUM];
	struct regmap *regmap_sfr;
	struct regmap *regmap_dmic_aud[VTS_S_LIF_DMIC_AUD_NUM];
	struct clk *clk_src;
	struct clk *clk_src1;
	struct clk *clk_mux_dmic_aud;
	struct clk *clk_mux_serial_lif;
	struct clk *clk_dmic_aud_pad;
	struct clk *clk_dmic_aud_div2;
	struct clk *clk_dmic_aud;
	struct clk *clk_serial_lif;
	struct pinctrl *pinctrl;
	struct delayed_work mute_work;
	unsigned int mute_ms;
	bool mute_enable;

	/* data */
	unsigned int gain_mode[VTS_S_LIF_DMIC_AUD_NUM];
	unsigned int max_scale_gain[VTS_S_LIF_DMIC_AUD_NUM];
	unsigned int control_dmic_aud[VTS_S_LIF_DMIC_AUD_NUM];
	/* atomic_t dmic_state[VTS_S_LIF_DMIC_AUD_NUM]; */
	unsigned int dmic_en[VTS_S_LIF_DMIC_AUD_NUM];
	unsigned int channel_map;
	unsigned int channels;
	unsigned int rate;
	unsigned int width;
	unsigned int clk_table_id;
	unsigned int slif_dump_enabled;

	/* sync */
	wait_queue_head_t ipc_wait_queue;
	spinlock_t ipc_spinlock;
	struct mutex ipc_mutex;
	spinlock_t state_spinlock;
	struct wake_lock wake_lock;

	/* status */
	volatile bool enabled;
	volatile bool running;
	unsigned long state;
	unsigned long mode;
	unsigned int fmt;

	/* alsa data */
	struct snd_soc_component *cmpnt;
	struct snd_soc_card *card;

	/* ETC. */
	unsigned int last_array[10];
};

#endif /* __SND_SOC_VTS_S_LIF_H */
