#
# Makefile for the dynamic kernel loader of dsp driver
#

ccflags-y	+= -Idrivers/vision/dsp

obj-y		+= dsp-common.o
obj-y		+= dsp-dl-engine.o
obj-y		+= dsp-dl-linker.o
obj-y		+= dsp-dl-out-manager.o
obj-y		+= dsp-elf-loader.o
obj-y		+= dsp-gpt-manager.o
obj-y		+= dsp-hash.o
obj-y		+= dsp-lib-manager.o
obj-y		+= dsp-list.o
obj-y		+= dsp-llstack.o
obj-y		+= dsp-pm-manager.o
obj-y		+= dsp-rule-reader.o
obj-y		+= dsp-string-tree.o
obj-y		+= dsp-sxml.o
obj-y		+= dsp-tlsf-allocator.o
obj-y		+= dsp-xml-parser.o
