/*
 * Copyright (c) 2018 Samsung Electronics Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * Common Clock Framework support for Exynos9830 SoC.
 */

#include <linux/clk.h>
#include <linux/clkdev.h>
#include <linux/clk-provider.h>
#include <linux/of.h>
#include <linux/of_address.h>
#include <soc/samsung/cal-if.h>
#include <dt-bindings/clock/exynos9830.h>

#include "../../soc/samsung/cal-if/exynos9830/cmucal-vclk.h"
#include "../../soc/samsung/cal-if/exynos9830/cmucal-node.h"
#include "../../soc/samsung/cal-if/exynos9830/cmucal-qch.h"
#include "../../soc/samsung/cal-if/exynos9830/clkout_exynos9830.h"
#include "composite.h"

static struct samsung_clk_provider *exynos9830_clk_provider;
/*
 * list of controller registers to be saved and restored during a
 * suspend/resume cycle.
 */
/* fixed rate clocks generated outside the soc */
struct samsung_fixed_rate exynos9830_fixed_rate_ext_clks[] __initdata = {
	FRATE(OSCCLK, "fin_pll", NULL, 0, 26000000),
};

/* HWACG VCLK */
struct init_vclk exynos9830_mfc0_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_MFC0_MFC0, MUX_CLKCMU_MFC0_MFC0_USER, "UMUX_CLKCMU_MFC0_MFC0", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_MFC0_WFD, MUX_CLKCMU_MFC0_WFD_USER, "UMUX_CLKCMU_MFC0_WFD", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_MFC0, MFC0_QCH, "GATE_MFC0", "UMUX_CLKCMU_MFC0_MFC0", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_MFC0D0_S1, SYSMMU_MFC0D0_QCH_S1, "GATE_SYSMMU_MFC0D0_S1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_MFC0D0_S2, SYSMMU_MFC0D0_QCH_S2, "GATE_SYSMMU_MFC0D0_S2", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_MFC0D1_S1, SYSMMU_MFC0D1_QCH_S1, "GATE_SYSMMU_MFC0D1_S1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_MFC0D1_S2, SYSMMU_MFC0D1_QCH_S2, "GATE_SYSMMU_MFC0D1_S2", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WFD, WFD_QCH, "GATE_WFD", "UMUX_CLKCMU_MFC0_WFD", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_npu00_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_NPUC_BUS, MUX_CLKCMU_NPUC_BUS_USER, "UMUX_CLKCMU_NPUC_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(GATE_IP_NPUC_ACLK, IP_NPUC_QCH_ACLK, "GATE_IP_NPUC_ACLK", "UMUX_CLKCMU_NPUC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IP_NPUC_PCLK, IP_NPUC_QCH_PCLK, "GATE_IP_NPUC_PCLK", "UMUX_CLKCMU_NPUC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_NPUD_UNIT0, NPUD_UNIT0_QCH, "GATE_NPUD_UNIT0", "UMUX_CLKCMU_NPUC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_NPUD_UNIT1, NPUD_UNIT1_QCH, "GATE_NPUD_UNIT1", "UMUX_CLKCMU_NPUC_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_npu01_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_NPU_BUS, MUX_CLKCMU_NPU_BUS_USER, "UMUX_CLKCMU_NPU_BUS", NULL, 0, 0, NULL),
};

struct init_vclk exynos9830_npu10_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_NPU10_BUS, MUX_CLKCMU_NPU10_BUS_USER, "UMUX_CLKCMU_NPU10_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(GATE_IP_NPU10_ACLK, IP_NPU10_QCH_ACLK, "GATE_IP_NPU10_ACLK", "UMUX_CLKCMU_NPU10_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IP_NPU10_PCLK, IP_NPU10_QCH_PCLK, "GATE_IP_NPU10_PCLK", "UMUX_CLKCMU_NPU10_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_NPU10D_UNIT0, NPU10_NPU10D_UNIT0_QCH, "GATE_NPU10D_UNIT0", "UMUX_CLKCMU_NPU10_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_NPU10D_UNIT1, NPU10_NPU10D_UNIT1_QCH, "GATE_NPU10D_UNIT1", "UMUX_CLKCMU_NPU10_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_npu11_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_NPU11_BUS, MUX_CLKCMU_NPU11_BUS_USER, "UMUX_CLKCMU_NPU11_BUS", NULL, 0, 0, NULL),
};

struct init_vclk exynos9830_peric0_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_PERIC0_BUS, MUX_CLKCMU_PERIC0_BUS_USER, "UMUX_CLKCMU_PERIC0_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_PERIC0_USI_I2C, MUX_CLKCMU_PERIC0_USI_I2C_USER, "UMUX_CLKCMU_PERIC0_USI_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_GPIO_PERIC0, GPIO_PERIC0_QCH, "GATE_GPIO_PERIC0", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_PWM, PERIC0_TOP1_QCH_PWM, "GATE_PERIC0_TOP1_PWM", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_UART_DBG, PERIC0_TOP0_QCH_UART_DBG, "GATE_PERIC0_TOP0_QCH_UART_DBG", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, "console-pclk0"),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI00_USI, PERIC0_TOP0_QCH_USI00_USI, "GATE_PERIC0_TOP0_QCH_USI00_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI00_I2C, PERIC0_TOP0_QCH_USI00_I2C, "GATE_PERIC0_TOP0_QCH_USI00_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI01_USI, PERIC0_TOP0_QCH_USI01_USI, "GATE_PERIC0_TOP0_QCH_USI01_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI01_I2C, PERIC0_TOP0_QCH_USI01_I2C, "GATE_PERIC0_TOP0_QCH_USI01_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI02_USI, PERIC0_TOP0_QCH_USI02_USI, "GATE_PERIC0_TOP0_QCH_USI02_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI02_I2C, PERIC0_TOP0_QCH_USI02_I2C, "GATE_PERIC0_TOP0_QCH_USI02_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI03_USI, PERIC0_TOP0_QCH_USI03_USI, "GATE_PERIC0_TOP0_QCH_USI03_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI03_I2C, PERIC0_TOP0_QCH_USI03_I2C, "GATE_PERIC0_TOP0_QCH_USI03_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
#ifdef CONFIG_SENSORS_FINGERPRINT
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI04_USI, PERIC0_TOP0_QCH_USI04_USI, "GATE_PERIC0_TOP0_QCH_USI04_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, "fp-spi-pclk"),
#else
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI04_USI, PERIC0_TOP0_QCH_USI04_USI, "GATE_PERIC0_TOP0_QCH_USI04_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
#endif
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI04_I2C, PERIC0_TOP0_QCH_USI04_I2C, "GATE_PERIC0_TOP0_QCH_USI04_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP0_QCH_USI05_USI, PERIC0_TOP0_QCH_USI05_USI, "GATE_PERIC0_TOP0_QCH_USI05_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_QCH_USI05_I2C, PERIC0_TOP1_QCH_USI05_I2C, "GATE_PERIC0_TOP1_QCH_USI05_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_QCH_USI13_USI, PERIC0_TOP1_QCH_USI13_USI, "GATE_PERIC0_TOP1_QCH_USI13_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_QCH_USI13_I2C, PERIC0_TOP1_QCH_USI13_I2C, "GATE_PERIC0_TOP1_QCH_USI13_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_QCH_USI14_USI, PERIC0_TOP1_QCH_USI14_USI, "GATE_PERIC0_TOP1_QCH_USI14_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_QCH_USI14_I2C, PERIC0_TOP1_QCH_USI14_I2C, "GATE_PERIC0_TOP1_QCH_USI14_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_QCH_USI15_USI, PERIC0_TOP1_QCH_USI15_USI, "GATE_PERIC0_TOP1_QCH_USI15_USI", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC0_TOP1_QCH_USI15_I2C, PERIC0_TOP1_QCH_USI15_I2C, "GATE_PERIC0_TOP1_QCH_USI15_I2C", "UMUX_CLKCMU_PERIC0_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_peric1_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_PERIC1_BUS, MUX_CLKCMU_PERIC1_BUS_USER, "UMUX_CLKCMU_PERIC1_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_PERIC1_USI_I2C, MUX_CLKCMU_PERIC1_USI_I2C_USER, "UMUX_CLKCMU_PERIC1_USI_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_GPIO_PERIC1, GPIO_PERIC1_QCH, "GATE_GPIO_PERIC1", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_QCH_UART_BT, PERIC1_TOP0_QCH_UART_BT, "GATE_PERIC1_TOP0_QCH_UART_BT", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_QCH_USI06_USI, PERIC1_TOP0_QCH_USI06_USI, "GATE_PERIC1_TOP0_QCH_USI06_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_QCH_USI06_I2C, PERIC1_TOP0_QCH_USI06_I2C, "GATE_PERIC1_TOP0_QCH_USI06_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_QCH_USI07_USI, PERIC1_TOP0_QCH_USI07_USI, "GATE_PERIC1_TOP0_QCH_USI07_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_QCH_USI07_I2C, PERIC1_TOP0_QCH_USI07_I2C, "GATE_PERIC1_TOP0_QCH_USI07_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_QCH_USI08_USI, PERIC1_TOP0_QCH_USI08_USI, "GATE_PERIC1_TOP0_QCH_USI08_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP0_QCH_USI08_I2C, PERIC1_TOP0_QCH_USI08_I2C, "GATE_PERIC1_TOP0_QCH_USI08_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI09_USI, PERIC1_TOP1_QCH_USI09_USI, "GATE_PERIC1_TOP1_QCH_USI09_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI09_I2C, PERIC1_TOP1_QCH_USI09_I2C, "GATE_PERIC1_TOP1_QCH_USI09_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI10_USI, PERIC1_TOP1_QCH_USI10_USI, "GATE_PERIC1_TOP1_QCH_USI10_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI10_I2C, PERIC1_TOP1_QCH_USI10_I2C, "GATE_PERIC1_TOP1_QCH_USI10_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI11_USI, PERIC1_TOP1_QCH_USI11_USI, "GATE_PERIC1_TOP1_QCH_USI11_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI11_I2C, PERIC1_TOP1_QCH_USI11_I2C, "GATE_PERIC1_TOP1_QCH_USI11_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI16_USI, PERIC1_TOP1_QCH_USI16_USI, "GATE_PERIC1_TOP1_QCH_USI16_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI16_I2C, PERIC1_TOP1_QCH_USI16_I2C, "GATE_PERIC1_TOP1_QCH_USI16_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI17_USI, PERIC1_TOP1_QCH_USI17_USI, "GATE_PERIC1_TOP1_QCH_USI17_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI17_I2C, PERIC1_TOP1_QCH_USI17_I2C, "GATE_PERIC1_TOP1_QCH_USI17_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI12_USI, PERIC1_TOP1_QCH_USI12_USI, "GATE_PERIC1_TOP1_QCH_USI12_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI12_I2C, PERIC1_TOP1_QCH_USI12_I2C, "GATE_PERIC1_TOP1_QCH_USI12_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI18_USI, PERIC1_TOP1_QCH_USI18_USI, "GATE_PERIC1_TOP1_QCH_USI18_USI", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIC1_TOP1_QCH_USI18_I2C, PERIC1_TOP1_QCH_USI18_I2C, "GATE_PERIC1_TOP1_QCH_USI18_I2C", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI16_I3C_QCH_P, USI16_I3C_QCH_P, "GATE_USI16_I3C_QCH_P", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI16_I3C_QCH_S, USI16_I3C_QCH_S, "GATE_USI16_I3C_QCH_S", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_USI17_I3C_QCH_P, USI17_I3C_QCH_P, "GATE_USI17_I3C_QCH_P", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI17_I3C_QCH_S, USI17_I3C_QCH_S, "GATE_USI17_I3C_QCH_S", "UMUX_CLKCMU_PERIC1_BUS", 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
};

struct init_vclk exynos9830_peris_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_PERIS_BUS, MUX_CLKCMU_PERIS_BUS_USER, "UMUX_CLKCMU_PERIS_BUS", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_GIC, GIC_QCH, "GATE_GIC", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MCT, MCT_QCH, "GATE_MCT", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_OTP_CON_BIRA, OTP_CON_BIRA_QCH, "GATE_OTP_CON_BIRA", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_OTP_CON_TOP, OTP_CON_TOP_QCH, "GATE_OTP_CON_TOP", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PERIS_CMU_PERIS, PERIS_CMU_PERIS_QCH, "GATE_PERIS_CMU_PERIS", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_PERIS, SYSREG_PERIS_QCH, "GATE_SYSREG_PERIS", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TMU_SUB, TMU_SUB_QCH, "GATE_TMU_SUB", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TMU_TOP, TMU_TOP_QCH, "GATE_TMU_TOP", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_CLUSTER0, WDT_CLUSTER0_QCH, "GATE_WDT_CLUSTER0", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_CLUSTER2, WDT_CLUSTER2_QCH, "GATE_WDT_CLUSTER2", "UMUX_CLKCMU_PERIS_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_ssp_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_SSP_BUS, MUX_CLKCMU_SSP_BUS_USER, "UMUX_CLKCMU_SSP_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(DOUT_CLK_SSP_BUSP, DIV_CLK_SSP_BUSP, "DOUT_CLK_SSP_BUSP", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_USS_SSPCORE, USS_SSPCORE_QCH, "GATE_USS_SSPCORE", "UMUX_CLKCMU_SSP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_D_TZPC_SSP, D_TZPC_SSP_QCH, "GATE_D_TZPC_SSP", "DOUT_CLK_SSP_BUSP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_SSP, SYSREG_SSP_QCH, "GATE_SYSREG_SSP", "DOUT_CLK_SSP_BUSP", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_tnr_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_TNR_BUS, MUX_CLKCMU_TNR_BUS_USER, "UMUX_CLKCMU_TNR_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(DOUT_CLK_TNR_BUSP, DIV_CLK_TNR_BUSP, "DOUT_CLK_TNR_BUSP", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_D_TZPC_TNR, D_TZPC_TNR_QCH, "GATE_D_TZPC_TNR", "DOUT_CLK_TNR_BUSP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_TNR_QCH_S1, SYSMMU_D0_TNR_QCH_S1, "GATE_SYSMMU_D0_TNR_QCH_S1", "UMUX_CLKCMU_TNR_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_TNR_QCH_S2, SYSMMU_D0_TNR_QCH_S2, "GATE_SYSMMU_D0_TNR_QCH_S2", "UMUX_CLKCMU_TNR_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_TNR_QCH_S1, SYSMMU_D1_TNR_QCH_S1, "GATE_SYSMMU_D1_TNR_QCH_S1", "UMUX_CLKCMU_TNR_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_TNR_QCH_S2, SYSMMU_D1_TNR_QCH_S2, "GATE_SYSMMU_D1_TNR_QCH_S2", "UMUX_CLKCMU_TNR_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_TNR, SYSREG_TNR_QCH, "GATE_SYSREG_TNR", "DOUT_CLK_TNR_BUSP", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TNR, TNR_QCH, "GATE_TNR", "UMUX_CLKCMU_TNR_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ORBMCH, ORBMCH_QCH, "GATE_ORBMCH", "UMUX_CLKCMU_TNR_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ORBMCH_C2, ORBMCH_QCH_C2, "GATE_ORBMCH_C2", "UMUX_CLKCMU_TNR_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_vra_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_VRA_BUS, MUX_CLKCMU_VRA_BUS_USER, "UMUX_CLKCMU_VRA_BUS", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_CLAHE, CLAHE_QCH, "GATE_CLAHE", "UMUX_CLKCMU_VRA_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_VRA_QCH_S1, SYSMMU_VRA_QCH_S1, "GATE_SYSMMU_VRA_QCH_S1", "UMUX_CLKCMU_VRA_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_VRA_QCH_S2, SYSMMU_VRA_QCH_S2, "GATE_SYSMMU_VRA_QCH_S2", "UMUX_CLKCMU_VRA_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_vts_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_VTS_BUS, MUX_CLKCMU_VTS_BUS_USER, "UMUX_CLKCMU_VTS_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_VTS_RCO, MUX_CLKCMU_VTS_RCO_USER, "UMUX_CLKCMU_VTS_RCO", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLK_VTS_BUS, MUX_CLK_VTS_BUS, "UMUX_CLK_VTS_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_VTS_AUD0, MUX_CLKCMU_VTS_AUD0_USER, "UMUX_CLKCMU_VTS_AUD0", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_VTS_AUD1, MUX_CLKCMU_VTS_AUD1_USER, "UMUX_CLKCMU_VTS_AUD1", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLK_VTS_DMIC_AUD, MUX_CLK_VTS_DMIC_AUD, "UMUX_CLK_VTS_DMIC_AUD", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLK_VTS_SERIAL_LIF, MUX_CLK_VTS_SERIAL_LIF, "UMUX_CLK_VTS_SERIAL_LIF", NULL, 0, 0, NULL),
	HWACG_VCLK(GATE_CORTEXM4INTEGRATION_CPU, CORTEXM4INTEGRATION_QCH_CPU, "GATE_CORTEXM4INTEGRATION_CPU", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_AHB0_PCLK, DMIC_AHB0_QCH_PCLK, "GATE_AHB0_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_AHB1_PCLK, DMIC_AHB1_QCH_PCLK, "GATE_AHB1_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_AHB2_PCLK, DMIC_AHB2_QCH_PCLK, "GATE_AHB2_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_AHB3_PCLK, DMIC_AHB3_QCH_PCLK, "GATE_AHB3_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_AHB4_PCLK, DMIC_AHB4_QCH_PCLK, "GATE_AHB4_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_AHB5_PCLK, DMIC_AHB5_QCH_PCLK, "GATE_AHB5_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_AUD0_PCLK, DMIC_AUD0_QCH_PCLK, "GATE_DMIC_AUD0_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_AUD0_DMIC, DMIC_AUD0_QCH_DMIC, "GATE_DMIC_AUD0_DMIC", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_AUD1_PCLK, DMIC_AUD1_QCH_PCLK, "GATE_DMIC_AUD1_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_AUD1_DMIC, DMIC_AUD1_QCH_DMIC, "GATE_DMIC_AUD1_DMIC", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_AUD2_PCLK, DMIC_AUD2_QCH_PCLK, "GATE_DMIC_AUD2_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_AUD2_DMIC, DMIC_AUD2_QCH_DMIC, "GATE_DMIC_AUD2_DMIC", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_IF0_PCLK, DMIC_IF0_QCH_PCLK, "GATE_DMIC_IF0_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_IF0_DMIC, DMIC_IF0_QCH_DMIC, "GATE_DMIC_IF0_DMIC", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_IF1_PCLK, DMIC_IF1_QCH_PCLK, "GATE_DMIC_IF1_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_IF1_DMIC, DMIC_IF1_QCH_DMIC, "GATE_DMIC_IF1_DMIC", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_IF2_PCLK, DMIC_IF2_QCH_PCLK, "GATE_DMIC_IF2_PCLK", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DMIC_IF2_DMIC, DMIC_IF2_QCH_DMIC, "GATE_DMIC_IF2_DMIC", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_GPIO_VTS, GPIO_VTS_QCH, "GATE_GPIO_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC0, HWACG_SYS_DMIC0_QCH, "GATE_HWACG_SYS_DMIC0", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC1, HWACG_SYS_DMIC1_QCH, "GATE_HWACG_SYS_DMIC1", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC2, HWACG_SYS_DMIC2_QCH, "GATE_HWACG_SYS_DMIC2", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC3, HWACG_SYS_DMIC3_QCH, "GATE_HWACG_SYS_DMIC3", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC4, HWACG_SYS_DMIC4_QCH, "GATE_HWACG_SYS_DMIC4", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_HWACG_SYS_DMIC5, HWACG_SYS_DMIC5_QCH, "GATE_HWACG_SYS_DMIC5", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_ABOX_VTS, MAILBOX_ABOX_VTS_QCH, "GATE_MAILBOX_ABOX_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_AP_VTS, MAILBOX_AP_VTS_QCH, "GATE_MAILBOX_AP_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SWEEPER_C_VTS, SWEEPER_C_VTS_QCH, "GATE_SWEEPER_C_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_VTS, SYSREG_VTS_QCH, "GATE_SYSREG_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TIMER_VTS, TIMER_QCH, "GATE_TIMER_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TIMER1_VTS, TIMER1_QCH, "GATE_TIMER1_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TIMER2_VTS, TIMER2_QCH, "GATE_TIMER2_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_VTS, WDT_VTS_QCH, "GATE_WDT_VTS", "UMUX_CLKCMU_VTS_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_apm_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_DLL, MUX_DLL_USER, "UMUX_DLL", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLKMUX_APM_RCO, MUX_CLKMUX_APM_RCO_USER, "UMUX_CLKMUX_APM_RCO", NULL, 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_GREBEINTEGRATION_GREBE, GREBEINTEGRATION_QCH_GREBE, "GATE_GREBEINTEGRATION_GREBE", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_GREBEINTEGRATION_DBG, GREBEINTEGRATION_QCH_DBG, "GATE_GREBEINTEGRATION_DBG", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DBGCORE_GREBE, SS_DBGCORE_QCH_GREBE, "GATE_DBGCORE_GREBE", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DBGCORE_DBG, SS_DBGCORE_QCH_DBG, "GATE_DBGCORE_DBG", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_INTMEM, INTMEM_QCH, "GATE_INTMEM_QCH", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_AP, MAILBOX_APM_AP_QCH, "GATE_MAILBOX_APM_AP", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_APM_VTS, MAILBOX_APM_VTS_QCH, "GATE_MAILBOX_APM_VTS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MAILBOX_AP_DBGCORE, MAILBOX_AP_DBGCORE_QCH, "GATE_MAILBOX_AP_DBGCORE", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PEM, PEM_QCH, "GATE_PEM_QCH", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PMU_INTR_GEN, PMU_INTR_GEN_QCH, "GATE_PMU_INTR_GEN", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_RSTNSYNC_CLK_APM_BUS_GREBE, RSTNSYNC_CLK_APM_BUS_QCH_GREBE, "GATE_RSTNSYNC_CLK_APM_BUS_GREBE", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_RSTNSYNC_CLK_APM_BUS_GREBE_DBG, RSTNSYNC_CLK_APM_BUS_QCH_GREBE_DBG, "GATE_RSTNSYNC_CLK_APM_BUS_GREBE_DBG", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SPEEDY_APM, SPEEDY_APM_QCH, "GATE_SPEEDY_APM", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SPEEDY_SUB_APM, SPEEDY_SUB_APM_QCH, "GATE_SPEEDY_SUB_APM", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_APM, SYSREG_APM_QCH, "GATE_SYSREG_APM", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_APM, WDT_APM_QCH, "GATE_WDT_APM", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_aud_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLK_AUD_UAIF6, MUX_CLK_AUD_UAIF6, "UMUX_CLK_AUD_UAIF6", NULL, 0, 0, NULL),
	HWACG_VCLK(GATE_ABOX_ACLK, ABOX_QCH_ACLK, "GATE_ABOX_ACLK", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK_DSIF, ABOX_QCH_BCLK_DSIF, "GATE_ABOX_BCLK_DSIF", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK0, ABOX_QCH_BCLK0, "GATE_ABOX_BCLK0", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK1, ABOX_QCH_BCLK1, "GATE_ABOX_BCLK1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK2, ABOX_QCH_BCLK2, "GATE_ABOX_BCLK2", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK3, ABOX_QCH_BCLK3, "GATE_ABOX_BCLK3", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK4, ABOX_QCH_BCLK4, "GATE_ABOX_BCLK4", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK5, ABOX_QCH_BCLK5, "GATE_ABOX_BCLK5", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_BCLK6, ABOX_QCH_BCLK6, "GATE_ABOX_BCLK6", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ABOX_CNT, ABOX_QCH_CNT, "GATE_ABOX_CNT", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_AUD_CMU_AUD, AUD_CMU_AUD_QCH, "GATE_AUD_CMU_AUD", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PPMU_AUD, PPMU_AUD_QCH, "GATE_PPMU_AUD", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SMMU_AUD_S1, SMMU_AUD_QCH_S1, "GATE_SMMU_AUD_S1", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SMMU_AUD_S2, SMMU_AUD_QCH_S2, "GATE_SMMU_AUD_S2", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_AUD, SYSREG_AUD_QCH, "GATE_SYSREG_AUD", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_WDT_AUD, WDT_AUD_QCH, "GATE_WDT_AUD", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_bus1_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_BUS1_BUS, MUX_CLKCMU_BUS1_BUS_USER, "UMUX_CLKCMU_BUS1_BUS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLKCMU_BUS1_SSS, MUX_CLKCMU_BUS1_SSS_USER, "UMUX_CLKCMU_BUS1_SSS", NULL, 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_PDMA, PDMA_QCH, "GATE_PDMA", "UMUX_CLKCMU_BUS1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SBIC, SBIC_QCH, "GATE_SBIC", "UMUX_CLKCMU_BUS1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_RTIC, RTIC_QCH, "GATE_RTIC", "UMUX_CLKCMU_BUS1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SSS, SSS_QCH, "GATE_SSS", "UMUX_CLKCMU_BUS1_SSS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SPDMA, SPDMA_QCH, "GATE_SPDMA", "UMUX_CLKCMU_BUS1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_BUS1, SYSREG_BUS1_QCH, "GATE_SYSREG_BUS1", "UMUX_CLKCMU_BUSC_BUS", 0, VCLK_GATE, NULL),
	
};

struct init_vclk exynos9830_cmgp_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_CMGP_BUS, MUX_CLKCMU_CMGP_BUS_USER, "UMUX_CLKCMU_CMGP_BUS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLKCMU_CMGP_RCO, MUX_CLKCMU_CMGP_RCO_USER, "UMUX_CLKCMU_CMGP_RCO", NULL, 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_ADC_CMGP_S0, ADC_CMGP_QCH_S0, "GATE_ADC_CMGP_S0", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ADC_CMGP_S1, ADC_CMGP_QCH_S1, "GATE_ADC_CMGP_S1", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_ADC_CMGP_OSC, ADC_CMGP_QCH_OSC, "GATE_ADC_CMGP_OSC", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CMGP_CMU_CMGP, CMGP_CMU_CMGP_QCH, "GATE_CMGP_CMU_CMGP", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_GPIO_CMGP, GPIO_CMGP_QCH, "GATE_GPIO_CMGP", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP0, I2C_CMGP0_QCH, "GATE_I2C_CMGP0", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP1, I2C_CMGP1_QCH, "GATE_I2C_CMGP1", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP2, I2C_CMGP2_QCH, "GATE_I2C_CMGP2", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_I2C_CMGP3, I2C_CMGP3_QCH, "GATE_I2C_CMGP3", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_CMGP, SYSREG_CMGP_QCH, "GATE_SYSREG_CMGP", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_CMGP2APM, SYSREG_CMGP2APM_QCH, "GATE_SYSREG_CMGP2APM", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_CMGP2PMU_AP, SYSREG_CMGP2PMU_AP_QCH, "GATE_SYSREG_CMGP2PMU_AP", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP0, USI_CMGP0_QCH, "GATE_USI_CMGP0", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP1, USI_CMGP1_QCH, "GATE_USI_CMGP1", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP2, USI_CMGP2_QCH, "GATE_USI_CMGP2", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USI_CMGP3, USI_CMGP3_QCH, "GATE_USI_CMGP3", "UMUX_CLKCMU_CMGP_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_top_hwacg_vclks[] __initdata = {
	HWACG_VCLK(GATE_CMU_TOP_CMUREF, CMU_TOP_CMUREF_QCH, "GATE_CMU_TOP_CMUREF", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DFTMUX_TOP_CIS_CLK0, DFTMUX_TOP_QCH_CIS_CLK0, "GATE_DFTMUX_TOP_QCH_CIS_CLK0", NULL, 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_DFTMUX_TOP_CIS_CLK1, DFTMUX_TOP_QCH_CIS_CLK1, "GATE_DFTMUX_TOP_QCH_CIS_CLK1", NULL, 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_DFTMUX_TOP_CIS_CLK2, DFTMUX_TOP_QCH_CIS_CLK2, "GATE_DFTMUX_TOP_QCH_CIS_CLK2", NULL, 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_DFTMUX_TOP_CIS_CLK3, DFTMUX_TOP_QCH_CIS_CLK3, "GATE_DFTMUX_TOP_QCH_CIS_CLK3", NULL, 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_DFTMUX_TOP_CIS_CLK4, DFTMUX_TOP_QCH_CIS_CLK4, "GATE_DFTMUX_TOP_QCH_CIS_CLK4", NULL, 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_DFTMUX_TOP_CIS_CLK5, DFTMUX_TOP_QCH_CIS_CLK5, "GATE_DFTMUX_TOP_QCH_CIS_CLK5", NULL, 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_OTP, OTP_QCH, "GATE_OTP", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_core_hwacg_vclks[] __initdata = {
	HWACG_VCLK(GATE_TREX_D_CORE, TREX_D_CORE_QCH, "GATE_TREX_D_CORE", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TREX_P0_CORE, TREX_P0_CORE_QCH, "GATE_TREX_P0_CORE", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_TREX_P1_CORE, TREX_P1_CORE_QCH, "GATE_TREX_P1_CORE", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_csis_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_CSIS_BUS, MUX_CLKCMU_CSIS_BUS_USER, "UMUX_CLKCMU_CSIS_BUS", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(UMUX_CLKCMU_CSIS_OIS_MCU, MUX_CLKCMU_CSIS_OIS_MCU_USER, "UMUX_CLKCMU_CSIS_OIS_MCU", NULL, 0, VCLK_GATE, NULL),
	
	HWACG_VCLK(GATE_CSIS_PDP_C2_CSIS, CSIS_PDP_QCH_C2_CSIS, "GATE_CSIS_PDP_C2_CSIS", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_CSIS0, CSIS_PDP_QCH_CSIS0, "GATE_CSIS_PDP_CSIS0", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_CSIS1, CSIS_PDP_QCH_CSIS1, "GATE_CSIS_PDP_CSIS1", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_CSIS2, CSIS_PDP_QCH_CSIS2, "GATE_CSIS_PDP_CSIS2", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_CSIS3, CSIS_PDP_QCH_CSIS3, "GATE_CSIS_PDP_CSIS3", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_CSIS4, CSIS_PDP_QCH_CSIS4, "GATE_CSIS_PDP_CSIS4", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_CSIS_DMA, CSIS_PDP_QCH_CSIS_DMA, "GATE_CSIS_PDP_CSIS_DMA", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_TOP, CSIS_PDP_QCH_PDP_TOP, "GATE_CSIS_PDP_TOP", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_CSIS_PDP_CSIS5, CSIS_PDP_QCH_CSIS5, "GATE_CSIS_PDP_CSIS5", "UMUX_CLKCMU_CSIS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_OIS_MCU_TOP_A, OIS_MCU_TOP_QCH_A, "GATE_OIS_MCU_TOP_A", "UMUX_CLKCMU_CSIS_OIS_MCU", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_OIS_MCU_TOP_H, OIS_MCU_TOP_QCH_H, "GATE_OIS_MCU_TOP_H", "UMUX_CLKCMU_CSIS_OIS_MCU", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_OIS_MCU_TOP_D, OIS_MCU_TOP_QCH_D, "GATE_OIS_MCU_TOP_D", "UMUX_CLKCMU_CSIS_OIS_MCU", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_CSIS_QCH_S1, SYSMMU_D0_CSIS_QCH_S1, "GATE_SYSMMU_D0_CSIS_S1", "UMUX_CLKCMU_CSIS_OIS_MCU", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_CSIS_QCH_S2, SYSMMU_D0_CSIS_QCH_S2, "GATE_SYSMMU_D0_CSIS_S2", "UMUX_CLKCMU_CSIS_OIS_MCU", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_CSIS_QCH_S1, SYSMMU_D1_CSIS_QCH_S1, "GATE_SYSMMU_D1_CSIS_S1", "UMUX_CLKCMU_CSIS_OIS_MCU", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_CSIS_QCH_S2, SYSMMU_D1_CSIS_QCH_S2, "GATE_SYSMMU_D1_CSIS_S2", "UMUX_CLKCMU_CSIS_OIS_MCU", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_dns_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_DNS_BUS, MUX_CLKCMU_DNS_BUS_USER, "UMUX_CLKCMU_DNS_BUS", NULL, 0, VCLK_GATE, NULL),

	HWACG_VCLK(GATE_DNS, DNS_QCH, "GATE_DNS", "UMUX_CLKCMU_DNS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNS_S1, SYSMMU_DNS_QCH_S1, "GATE_SYSMMU_DNS_S1", "UMUX_CLKCMU_DNS_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNS_S2, SYSMMU_DNS_QCH_S2, "GATE_SYSMMU_DNS_S2", "UMUX_CLKCMU_DNS_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_dpu_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_DPU_BUS, MUX_CLKCMU_DPU_BUS_USER, "UMUX_CLKCMU_DPU_BUS", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_DPU_DPU, DPU_QCH_DPU, "GATE_DPU_QCH_DPU", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DPU_DPU_DMA, DPU_QCH_DPU_DMA, "GATE_DPU_QCH_DPU_DMA", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DPU_DPU_DPP, DPU_QCH_DPU_DPP, "GATE_DPU_QCH_DPU_DPP", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DPU_DPU_WB_MUX, DPU_QCH_DPU_WB_MUX, "GATE_DPU_QCH_DPU_WB_MUX", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DPU_CMU_DPU, DPU_CMU_DPU_QCH, "GATE_DPU_CMU_DPU", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DPUD0_S1, SYSMMU_DPUD0_QCH_S1, "GATE_SYSMMU_DPUD0_S1", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DPUD0_S2, SYSMMU_DPUD0_QCH_S2, "GATE_SYSMMU_DPUD0_S2", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DPUD1_S1, SYSMMU_DPUD1_QCH_S1, "GATE_SYSMMU_DPUD1_S1", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DPUD1_S2, SYSMMU_DPUD1_QCH_S2, "GATE_SYSMMU_DPUD1_S2", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DPUD2_S1, SYSMMU_DPUD2_QCH_S1, "GATE_SYSMMU_DPUD2_S1", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DPUD2_S2, SYSMMU_DPUD2_QCH_S2, "GATE_SYSMMU_DPUD2_S2", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSREG_DPU, SYSREG_DPU_QCH, "GATE_SYSREG_DPU", "UMUX_CLKCMU_DPU_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_dsp0_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_DSP_BUS, MUX_CLKCMU_DSP_BUS_USER, "UMUX_CLKCMU_DSP_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(GATE_IP_DSP, IP_DSP_QCH, "GATE_IP_DSP", "UMUX_CLKCMU_DSP_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_dsp1_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_DSP1_BUS, MUX_CLKCMU_DSP1_BUS_USER, "UMUX_CLKCMU_DSP1_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(GATE_IP_DSP1, IP_DSP1_QCH, "GATE_IP_DSP1", "UMUX_CLKCMU_DSP1_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_dsp2_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_DSP2_BUS, MUX_CLKCMU_DSP2_BUS_USER, "UMUX_CLKCMU_DSP2_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(GATE_IP_DSP2, IP_DSP2_QCH, "GATE_IP_DSP2", "UMUX_CLKCMU_DSP2_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_dnc_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_DNC_BUS, MUX_CLKCMU_DNC_BUS_USER, "UMUX_CLKCMU_DNC_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_DNC_BUSM, MUX_CLKCMU_DNC_BUSM_USER, "UMUX_CLKCMU_DNC_BUSM", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_ADM_DAP_DNC, ADM_DAP_DNC_QCH, "GATE_ADM_DAP_DNC", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_IP_DSPC, IP_DSPC_QCH, "GATE_IP_DSPC", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNC0_S1, SYSMMU_DNC0_QCH_S1, "GATE_SYSMMU_DNC0_S1", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNC0_S2, SYSMMU_DNC0_QCH_S2, "GATE_SYSMMU_DNC0_S2", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNC1_S1, SYSMMU_DNC1_QCH_S1, "GATE_SYSMMU_DNC1_S1", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNC1_S2, SYSMMU_DNC1_QCH_S2, "GATE_SYSMMU_DNC1_S2", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNC2_S1, SYSMMU_DNC2_QCH_S1, "GATE_SYSMMU_DNC2_S1", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_DNC2_S2, SYSMMU_DNC2_QCH_S2, "GATE_SYSMMU_DNC2_S2", "UMUX_CLKCMU_DNC_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_g2d_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_G2D_G2D, MUX_CLKCMU_G2D_G2D_USER, "UMUX_CLKCMU_G2D_G2D", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_G2D_MSCL, MUX_CLKCMU_G2D_MSCL_USER, "UMUX_CLKCMU_G2D_MSCL", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_G2D, G2D_QCH, "GATE_G2D", "UMUX_CLKCMU_G2D_G2D", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_JPEG, JPEG_QCH, "GATE_JPEG", "UMUX_CLKCMU_G2D_MSCL", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_JSQZ, JSQZ_QCH, "GATE_JSQZ", "UMUX_CLKCMU_G2D_MSCL", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MSCL, MSCL_QCH, "GATE_MSCL", "UMUX_CLKCMU_G2D_MSCL", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_G2D_S1, SYSMMU_D0_G2D_QCH_S1, "GATE_SYSMMU_D0_G2D_S1", "UMUX_CLKCMU_G2D_G2D", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_G2D_S2, SYSMMU_D0_G2D_QCH_S2, "GATE_SYSMMU_D0_G2D_S2", "UMUX_CLKCMU_G2D_G2D", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_G2D_S1, SYSMMU_D1_G2D_QCH_S1, "GATE_SYSMMU_D1_G2D_S1", "UMUX_CLKCMU_G2D_G2D", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_G2D_S2, SYSMMU_D1_G2D_QCH_S2, "GATE_SYSMMU_D1_G2D_S2", "UMUX_CLKCMU_G2D_G2D", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D2_G2D_S1, SYSMMU_D2_G2D_QCH_S1, "GATE_SYSMMU_D2_G2D_S1", "UMUX_CLKCMU_G2D_G2D", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D2_G2D_S2, SYSMMU_D2_G2D_QCH_S2, "GATE_SYSMMU_D2_G2D_S2", "UMUX_CLKCMU_G2D_G2D", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_g3d_hwacg_vclks[] __initdata = {
	HWACG_VCLK(GATE_GPU, GPU_QCH, "GATE_GPU", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_hsi0_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_HSI0_BUS, MUX_CLKCMU_HSI0_BUS_USER, "UMUX_CLKCMU_HSI0_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_USB31DRD, MUX_CLKCMU_HSI0_USB31DRD_USER, "UMUX_CLKCMU_HSI0_USB31DRD", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_USBDP_DEBUG, MUX_CLKCMU_HSI0_USBDP_DEBUG_USER, "UMUX_CLKCMU_HSI0_USBDP_DEBUG", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI0_DPGTC, MUX_CLKCMU_HSI0_DPGTC_USER, "UMUX_CLKCMU_HSI0_DPGTC", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_DP_LINK_PCLK, DP_LINK_QCH_PCLK, "GATE_DP_LINK_PCLK", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_DP_LINK_GTC_CLK, DP_LINK_QCH_GTC_CLK, "GATE_DP_LINK_GTC_CLK", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_USB, SYSMMU_USB_QCH, "GATE_SYSMMU_USB", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB31DRD_REF, USB31DRD_QCH_REF, "GATE_USB31DRD_REF", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB31DRD_SLV_CTRL, USB31DRD_QCH_SLV_CTRL, "GATE_USB31DRD_SLV_CTRL", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB31DRD_SLV_LINK, USB31DRD_QCH_SLV_LINK, "GATE_USB31DRD_SLV_LINK", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB31DRD_APB, USB31DRD_QCH_APB, "GATE_USB31DRD_APB", NULL, 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_USB31DRD_PCS, USB31DRD_QCH_PCS, "GATE_USB31DRD_PCS", NULL, 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_hsi1_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_HSI1_BUS, MUX_CLKCMU_HSI1_BUS_USER, "UMUX_CLKCMU_HSI1_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI1_MMC_CARD, MUX_CLKCMU_HSI1_MMC_CARD_USER, "UMUX_CLKCMU_HSI1_MMC_CARD", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI1_PCIE, MUX_CLKCMU_HSI1_PCIE_USER, "UMUX_CLKCMU_HSI1_PCIE", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI1_UFS_CARD, MUX_CLKCMU_HSI1_UFS_CARD_USER, "UMUX_CLKCMU_HSI1_UFS_CARD", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI1_UFS_EMBD, MUX_CLKCMU_HSI1_UFS_EMBD_USER, "UMUX_CLKCMU_HSI1_UFS_EMBD", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_MMC_CARD, MMC_CARD_QCH, "GATE_MMC_CARD", "UMUX_CLKCMU_HSI1_MMC_CARD", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN2_MSTR, PCIE_GEN2_QCH_MSTR, "GATE_PCIE_GEN2_QCH_MSTR", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN2_PCS, PCIE_GEN2_QCH_PCS, "GATE_PCIE_GEN2_QCH_PCS", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN2_PHY, PCIE_GEN2_QCH_PHY, "GATE_PCIE_GEN2_QCH_PHY", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN2_DBI, PCIE_GEN2_QCH_DBI, "GATE_PCIE_GEN2_QCH_DBI", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN2_APB, PCIE_GEN2_QCH_APB, "GATE_PCIE_GEN2_QCH_APB", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN2_REF, PCIE_GEN2_QCH_REF, "GATE_PCIE_GEN2_QCH_REF", "UMUX_CLKCMU_HSI1_PCIE", 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_APB, PCIE_GEN4_0_QCH_APB, "GATE_PCIE_GEN4_0_APB", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_DBI, PCIE_GEN4_0_QCH_DBI, "GATE_PCIE_GEN4_0_DBI", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_AXI, PCIE_GEN4_0_QCH_AXI, "GATE_PCIE_GEN4_0_AXI", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_PCS_APB, PCIE_GEN4_0_QCH_PCS_APB, "GATE_PCIE_GEN4_0_PCS_APB", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_REF, PCIE_GEN4_0_QCH_REF, "GATE_PCIE_GEN4_0_REQ", "UMUX_CLKCMU_HSI1_PCIE", 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_0_PMA_APB, PCIE_GEN4_0_QCH_PMA_APB, "GATE_PCIE_GEN4_0_PMA_APB", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_IA_GEN2, PCIE_IA_GEN2_QCH, "GATE_PCIE_IA_GEN2", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_IA_GEN4_0, PCIE_IA_GEN4_0_QCH, "GATE_PCIE_IA_GEN4_0", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_HSI1, SYSMMU_HSI1_QCH, "GATE_SYSMMU_HSI1", "UMUX_CLKCMU_HSI1_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_UFS_CARD, UFS_CARD_QCH, "GATE_UFS_CARD", "UMUX_CLKCMU_HSI1_UFS_CARD", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_UFS_CARD_FMP, UFS_CARD_QCH_FMP, "GATE_UFS_CARD_QCH_FMP", "UMUX_CLKCMU_HSI1_UFS_CARD", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_UFS_EMBD, UFS_EMBD_QCH, "GATE_UFS_EMBD", "UMUX_CLKCMU_HSI1_UFS_EMBD", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_UFS_EMBD_FMP, UFS_EMBD_QCH_FMP, "GATE_UFS_EMBD_QCH_FMP", "UMUX_CLKCMU_HSI1_UFS_EMBD", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_hsi2_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_HSI2_PCIE, MUX_CLKCMU_HSI2_PCIE_USER, "UMUX_CLKCMU_HSI2_PCIE", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_HSI2_BUS, MUX_CLKCMU_HSI2_BUS_USER, "UMUX_CLKCMU_HSI2_BUS", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_PCIE_GEN4_1_DBI, PCIE_GEN4_1_QCH_DBI, "GATE_PCIE_GEN4_1_DBI", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_AXI, PCIE_GEN4_1_QCH_AXI, "GATE_PCIE_GEN4_1_AXI", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_APB, PCIE_GEN4_1_QCH_APB, "GATE_PCIE_GEN4_1_APB", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_REF, PCIE_GEN4_1_QCH_REF, "GATE_PCIE_GEN4_1_REF", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE | VCLK_QCH_DIS, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_PCS_APB, PCIE_GEN4_1_QCH_PCS_APB, "GATE_PCIE_GEN4_1_PCS_APB", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_GEN4_1_PMA_APB, PCIE_GEN4_1_QCH_PMA_APB, "GATE_PCIE_GEN4_1_PMA_APB", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_PCIE_IA_GEN4_1, PCIE_IA_GEN4_1_QCH, "GATE_PCIE_IA_GEN4_1", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_HSI2, SYSMMU_HSI2_QCH, "GATE_SYSMMU_HSI2", "UMUX_CLKCMU_HSI2_PCIE", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_ipp_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_IPP_BUS, MUX_CLKCMU_IPP_BUS_USER, "UMUX_CLKCMU_IPP_BUS", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_SIPU_IPP, SIPU_IPP_QCH, "GATE_SIPU_IPP", "UMUX_CLKCMU_IPP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SIPU_IPP_C2_STAT, SIPU_IPP_QCH_C2_STAT, "GATE_SIPU_IPP_C2_STAT", "UMUX_CLKCMU_IPP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SIPU_IPP_C2_YDS, SIPU_IPP_QCH_C2_YDS, "GATE_SIPU_IPP_C2_YDS", "UMUX_CLKCMU_IPP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_IPP_S1, SYSMMU_IPP_QCH_S1, "GATE_SYSMMU_IPP_S1", "UMUX_CLKCMU_IPP_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_IPP_S2, SYSMMU_IPP_QCH_S2, "GATE_SYSMMU_IPP_S2", "UMUX_CLKCMU_IPP_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_itp_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_ITP_BUS, MUX_CLKCMU_ITP_BUS_USER, "UMUX_CLKCMU_ITP_BUS", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_ITP, ITP_QCH, "GATE_ITP", "UMUX_CLKCMU_ITP_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_mcsc_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_CLKCMU_MCSC_BUS, MUX_CLKCMU_MCSC_BUS_USER, "UMUX_CLKCMU_MCSC_BUS", NULL, 0, 0, NULL),
	HWACG_VCLK(UMUX_CLKCMU_MCSC_GDC, MUX_CLKCMU_MCSC_GDC_USER, "UMUX_CLKCMU_MCSC_GDC", NULL, 0, 0, NULL),

	HWACG_VCLK(GATE_C2AGENT_D0_MCSC, C2AGENT_D0_MCSC_QCH, "GATE_C2AGENT_D0_MCSC", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_C2AGENT_D1_MCSC, C2AGENT_D1_MCSC_QCH, "GATE_C2AGENT_D1_MCSC", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_C2AGENT_D2_MCSC, C2AGENT_D2_MCSC_QCH, "GATE_C2AGENT_D1_MCSC", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_GDC, GDC_QCH, "GATE_GDC", "UMUX_CLKCMU_MCSC_GDC", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_GDC_C2, GDC_QCH_C2, "GATE_GDC_C2", "UMUX_CLKCMU_MCSC_GDC", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MCSC, MCSC_QCH, "GATE_MCSC", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_MCSC_C2, MCSC_QCH_C2, "GATE_MCSC_C2", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_MCSC_S1, SYSMMU_D0_MCSC_QCH_S1, "GATE_SYSMMU_D0_MCSC_S1", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D0_MCSC_S2, SYSMMU_D0_MCSC_QCH_S2, "GATE_SYSMMU_D0_MCSC_S2", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_MCSC_S1, SYSMMU_D1_MCSC_QCH_S1, "GATE_SYSMMU_D1_MCSC_S1", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
	HWACG_VCLK(GATE_SYSMMU_D1_MCSC_S2, SYSMMU_D1_MCSC_QCH_S2, "GATE_SYSMMU_D1_MCSC_S2", "UMUX_CLKCMU_MCSC_BUS", 0, VCLK_GATE, NULL),
};

struct init_vclk exynos9830_mif_hwacg_vclks[] __initdata = {
	HWACG_VCLK(UMUX_MIF_DDRPHY2X, CLKMUX_MIF_DDRPHY2X, "UMUX_MIF_DDRPHY2X", NULL, 0, 0, NULL),
};

/* Special VCLK */
struct init_vclk exynos9830_apm_vclks[] __initdata = {
	VCLK(DOUT_CLKCMU_VTS_BUS, CLKCMU_VTS_BUS, "DOUT_CLKCMU_VTS_BUS", 0, 0, NULL),
	VCLK(DOUT_CLKCMU_CMGP_BUS, CLKCMU_CMGP_BUS, "DOUT_CLKCMU_CMGP_BUS", 0, 0, NULL),
};

struct init_vclk exynos9830_aud_vclks[] __initdata = {
	VCLK(DOUT_CLK_AUD_AUDIF, DIV_CLK_AUD_AUDIF, "DOUT_CLK_AUD_AUDIF", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_DSIF, DIV_CLK_AUD_DSIF, "DOUT_CLK_AUD_DSIF", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_SCLK, DIV_CLK_AUD_SCLK, "DOUT_CLK_AUD_SCLK", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_UAIF0, DIV_CLK_AUD_UAIF0, "DOUT_CLK_AUD_UAIF0", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_UAIF1, DIV_CLK_AUD_UAIF1, "DOUT_CLK_AUD_UAIF1", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_UAIF2, DIV_CLK_AUD_UAIF2, "DOUT_CLK_AUD_UAIF2", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_UAIF3, DIV_CLK_AUD_UAIF3, "DOUT_CLK_AUD_UAIF3", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_UAIF4, DIV_CLK_AUD_UAIF4, "DOUT_CLK_AUD_UAIF4", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_UAIF5, DIV_CLK_AUD_UAIF5, "DOUT_CLK_AUD_UAIF5", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_UAIF6, DIV_CLK_AUD_UAIF6, "DOUT_CLK_AUD_UAIF6", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_CPU_ACLK, DIV_CLK_AUD_CPU_ACLK, "DOUT_CLK_AUD_CPU_ACLK", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_BUS, DIV_CLK_AUD_BUS, "DOUT_CLK_AUD_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_BUSP, DIV_CLK_AUD_BUSP, "DOUT_CLK_AUD_BUSP", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_DMIC0, DIV_CLK_AUD_DMIC0, "DOUT_CLK_AUD_DMIC0", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_DMIC1, DIV_CLK_AUD_DMIC1, "DOUT_CLK_AUD_DMIC1", 0, 0, NULL),
	VCLK(DOUT_CLK_AUD_CNT, DIV_CLK_AUD_CNT, "DOUT_CLK_AUD_CNT", 0, 0, NULL),
	VCLK(PLL_OUT_AUD0, PLL_AUD0, "PLL_OUT_AUD0", 0, 0, NULL),
	VCLK(PLL_OUT_AUD1, PLL_AUD1, "PLL_OUT_AUD1", 0, 0, NULL),
};

struct init_vclk exynos9830_cmgp_vclks[] __initdata = {
	VCLK(DOUT_CLK_I2C_CMGP0, DIV_CLK_I2C_CMGP0, "DOUT_CLK_I2C_CMGP0", 0, 0, NULL),
	VCLK(DOUT_CLK_USI_CMGP1, DIV_CLK_USI_CMGP1, "DOUT_CLK_USI_CMGP1", 0, 0, NULL),
	VCLK(DOUT_CLK_USI_CMGP0, VCLK_DIV_CLK_USI_CMGP0, "DOUT_CLK_USI_CMGP0", 0, 0, NULL),
	VCLK(DOUT_CLK_USI_CMGP2, DIV_CLK_USI_CMGP2, "DOUT_CLK_USI_CMGP2", 0, 0, NULL),
	VCLK(DOUT_CLK_USI_CMGP3, DIV_CLK_USI_CMGP3, "DOUT_CLK_USI_CMGP3", 0, 0, NULL),
	VCLK(DOUT_CLK_CMGP_ADC, DIV_CLK_CMGP_ADC, "DOUT_CLK_CMGP_ADC", 0, 0, NULL),
	VCLK(DOUT_CLK_I2C_CMGP1, DIV_CLK_I2C_CMGP1, "DOUT_CLK_I2C_CMGP1", 0, 0, NULL),
	VCLK(DOUT_CLK_I2C_CMGP2, DIV_CLK_I2C_CMGP2, "DOUT_CLK_I2C_CMGP2", 0, 0, NULL),
	VCLK(DOUT_CLK_I2C_CMGP3, DIV_CLK_I2C_CMGP3, "DOUT_CLK_I2C_CMGP3", 0, 0, NULL),
	VCLK(DOUT_CLK_CMGP_BUS, DIV_CLK_CMGP_BUS, "DOUT_CLK_CMGP_BUS", 0, 0, NULL),
};

struct init_vclk exynos9830_top_vclks[] __initdata = {
	VCLK(CIS_CLK0, CLKCMU_CIS_CLK0, "CIS_CLK0", 0, 0, NULL),
	VCLK(CIS_CLK1, CLKCMU_CIS_CLK1, "CIS_CLK1", 0, 0, NULL),
	VCLK(CIS_CLK2, CLKCMU_CIS_CLK2, "CIS_CLK2", 0, 0, NULL),
	VCLK(CIS_CLK3, CLKCMU_CIS_CLK3, "CIS_CLK3", 0, 0, NULL),
	VCLK(CIS_CLK4, CLKCMU_CIS_CLK4, "CIS_CLK4", 0, 0, NULL),
	VCLK(CIS_CLK5, CLKCMU_CIS_CLK5, "CIS_CLK5", 0, 0, NULL),
	VCLK(PLL_OUT_MMC, PLL_MMC, "PLL_OUT_MMC", 0, 0, NULL),
	VCLK(DOUT_CLK_TOP_HSI0_BUS, VCLK_DIV_CLK_TOP_HSI0_BUS, "DOUT_CLK_TOP_HSI0_BUS", 0, 0, NULL),
};

struct init_vclk exynos9830_peric0_vclks[] __initdata = {
	VCLK(DOUT_CLK_PERIC0_USI00_USI, VCLK_DIV_CLK_PERIC0_USI00_USI, "DOUT_CLK_PERIC0_USI00_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC0_USI01_USI, VCLK_DIV_CLK_PERIC0_USI01_USI, "DOUT_CLK_PERIC0_USI01_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC0_USI02_USI, VCLK_DIV_CLK_PERIC0_USI02_USI, "DOUT_CLK_PERIC0_USI02_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC0_USI03_USI, VCLK_DIV_CLK_PERIC0_USI03_USI, "DOUT_CLK_PERIC0_USI03_USI", 0, 0, NULL),
#ifdef CONFIG_SENSORS_FINGERPRINT
	VCLK(DOUT_CLK_PERIC0_USI04_USI, VCLK_DIV_CLK_PERIC0_USI04_USI, "DOUT_CLK_PERIC0_USI04_USI", 0, 0, "fp-spi-sclk"),
#else
	VCLK(DOUT_CLK_PERIC0_USI04_USI, VCLK_DIV_CLK_PERIC0_USI04_USI, "DOUT_CLK_PERIC0_USI04_USI", 0, 0, NULL),
#endif
	VCLK(DOUT_CLK_PERIC0_USI05_USI, VCLK_DIV_CLK_PERIC0_USI05_USI, "DOUT_CLK_PERIC0_USI05_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC0_USI_I2C, DIV_CLK_PERIC0_USI_I2C, "DOUT_CLK_PERIC0_USI_I2C", 0, 0, NULL),
	VCLK(UART_DBG, VCLK_DIV_CLK_PERIC0_UART_DBG, "UART_DBG", 0, 0, "console-sclk0"),
	VCLK(DOUT_CLK_PERIC0_USI13_USI, VCLK_DIV_CLK_PERIC0_USI13_USI, "DOUT_CLK_PERIC0_USI13_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC0_USI14_USI, VCLK_DIV_CLK_PERIC0_USI14_USI, "DOUT_CLK_PERIC0_USI14_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC0_USI15_USI, VCLK_DIV_CLK_PERIC0_USI15_USI, "DOUT_CLK_PERIC0_USI15_USI", 0, 0, NULL),
};

struct init_vclk exynos9830_peric1_vclks[] __initdata = {
	VCLK(DOUT_CLK_PERIC1_UART_BT, VCLK_DIV_CLK_PERIC1_UART_BT, "DOUT_CLK_PERIC1_UART_BT", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI_I2C, DIV_CLK_PERIC1_USI_I2C, "DOUT_CLK_PERIC1_USI_I2C", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI06_USI, VCLK_DIV_CLK_PERIC1_USI06_USI, "DOUT_CLK_PERIC1_USI06_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI07_USI, VCLK_DIV_CLK_PERIC1_USI07_USI, "DOUT_CLK_PERIC1_USI07_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI08_USI, VCLK_DIV_CLK_PERIC1_USI08_USI, "DOUT_CLK_PERIC1_USI08_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI09_USI, VCLK_DIV_CLK_PERIC1_USI09_USI, "DOUT_CLK_PERIC1_USI09_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI10_USI, VCLK_DIV_CLK_PERIC1_USI10_USI, "DOUT_CLK_PERIC1_USI10_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI11_USI, VCLK_DIV_CLK_PERIC1_USI11_USI, "DOUT_CLK_PERIC1_USI11_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI12_USI, VCLK_DIV_CLK_PERIC1_USI12_USI, "DOUT_CLK_PERIC1_USI12_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI16_USI, VCLK_DIV_CLK_PERIC1_USI16_USI, "DOUT_CLK_PERIC1_USI16_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI17_USI, VCLK_DIV_CLK_PERIC1_USI17_USI, "DOUT_CLK_PERIC1_USI17_USI", 0, 0, NULL),
	VCLK(DOUT_CLK_PERIC1_USI18_USI, VCLK_DIV_CLK_PERIC1_USI18_USI, "DOUT_CLK_PERIC1_USI18_USI", 0, 0, NULL),
};

struct init_vclk exynos9830_vts_vclks[] __initdata = {
	VCLK(DOUT_CLK_VTS_DMIC_IF, DIV_CLK_VTS_DMIC_IF, "DOUT_CLK_VTS_DMIC_IF", 0, 0, NULL),
	VCLK(DOUT_CLK_VTS_DMIC_IF_DIV2, DIV_CLK_VTS_DMIC_IF_DIV2, "DOUT_CLK_VTS_DMIC_IF_DIV2", 0, 0, NULL),
	VCLK(DOUT_CLK_VTS_DMIC_IF_PAD, DIV_CLK_VTS_DMIC_IF_PAD, "DOUT_CLK_VTS_DMIC_IF_PAD", 0, 0, NULL),
	VCLK(DOUT_CLK_VTS_DMIC_AUD, DIV_CLK_VTS_DMIC_AUD, "DOUT_CLK_VTS_DMIC_AUD", 0, 0, NULL),
	VCLK(DOUT_CLK_VTS_DMIC_AUD_DIV2, DIV_CLK_VTS_DMIC_AUD_DIV2, "DOUT_CLK_VTS_DMIC_AUD_DIV2", 0, 0, NULL),
	VCLK(DOUT_CLK_VTS_DMIC_AUD_PAD, DIV_CLK_VTS_DMIC_AUD_PAD, "DOUT_CLK_VTS_DMIC_AUD_PAD", 0, 0, NULL),
	VCLK(DOUT_CLK_VTS_BUS, DIV_CLK_VTS_BUS, "DOUT_CLK_VTS_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_VTS_SERIAL_LIF, DIV_CLK_VTS_SERIAL_LIF, "DOUT_CLK_VTS_SERIAL_LIF", 0, 0, NULL),
};

struct init_vclk exynos9830_hsi1_vclks[] __initdata = {
	VCLK(DOUT_CLKCMU_HSI1_MMC_CARD, CLKCMU_HSI1_MMC_CARD, "DOUT_CLKCMU_HSI1_MMC_CARD", 0, 0, NULL),
	VCLK(UFS_EMBD, CLKCMU_HSI1_UFS_EMBD, "UFS_EMBD", 0, 0, NULL),
};

struct init_vclk exynos9830_hsi0_vclks[] __initdata = {
	VCLK(USB31DRD, VCLK_IP_USB31DRD, "USB31DRD", 0, 0, NULL),
};

struct init_vclk exynos9830_npu00_vclks[] __initdata = {
	VCLK(DOUT_CLK_NPUC_BUS, DIV_CLK_NPUC_BUS, "DOUT_CLK_NPUC_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_NPUC_BUSP, DIV_CLK_NPUC_BUSP, "DOUT_CLK_NPUC_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_npu01_vclks[] __initdata = {
	VCLK(DOUT_CLK_NPU_BUS, DIV_CLK_NPU_BUS, "DOUT_CLK_NPU_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_NPU_BUSP, DIV_CLK_NPU_BUSP, "DOUT_CLK_NPU_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_npu10_vclks[] __initdata = {
	VCLK(DOUT_CLK_NPU10_BUS, DIV_CLK_NPU10_BUS, "DOUT_CLK_NPU10_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_NPU10_BUSP, DIV_CLK_NPU10_BUSP, "DOUT_CLK_NPU10_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_npu11_vclks[] __initdata = {
	VCLK(DOUT_CLK_NPU11_BUS, DIV_CLK_NPU11_BUS, "DOUT_CLK_NPU11_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_NPU11_BUSP, DIV_CLK_NPU11_BUSP, "DOUT_CLK_NPU11_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_tnr_vclks[] __initdata = {
	VCLK(DOUT_CLK_TNR_BUS, DIV_CLK_TNR_BUS, "DOUT_CLK_TNR_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_TNR_BUSP, DIV_CLK_TNR_BUSP, "DOUT_CLK_TNR_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_vra_vclks[] __initdata = {
	VCLK(DOUT_CLK_VRA_BUS, DIV_CLK_VRA_BUS, "DOUT_CLK_VRA_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_VRA_BUSP, DIV_CLK_VRA_BUSP, "DOUT_CLK_VRA_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_csis_vclks[] __initdata = {
	VCLK(DOUT_CLK_CSIS_BUS, DIV_CLK_CSIS_BUS, "DOUT_CLK_CSIS_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_CSIS_BUSP, DIV_CLK_CSIS_BUSP, "DOUT_CLK_CSIS_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_dns_vclks[] __initdata = {
	VCLK(DOUT_CLK_DNS_BUS, DIV_CLK_DNS_BUS, "DOUT_CLK_DNS_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_DNS_BUSP, DIV_CLK_DNS_BUSP, "DOUT_CLK_DNS_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_dsp0_vclks[] __initdata = {
	VCLK(DOUT_CLK_DSP_BUS, DIV_CLK_DSP_BUS, "DOUT_CLK_DSP_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_DSP_BUSP, DIV_CLK_DSP_BUSP, "DOUT_CLK_DSP_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_dsp1_vclks[] __initdata = {
	VCLK(DOUT_CLK_DSP1_BUS, DIV_CLK_DSP1_BUS, "DOUT_CLK_DSP1_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_DSP1_BUSP, DIV_CLK_DSP1_BUSP, "DOUT_CLK_DSP1_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_dsp2_vclks[] __initdata = {
	VCLK(DOUT_CLK_DSP2_BUS, DIV_CLK_DSP2_BUS, "DOUT_CLK_DSP2_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_DSP2_BUSP, DIV_CLK_DSP2_BUSP, "DOUT_CLK_DSP2_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_dnc_vclks[] __initdata = {
	VCLK(DOUT_CLK_DNC_BUS, DIV_CLK_DNC_BUS, "DOUT_CLK_DNC_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_DNC_BUSP, DIV_CLK_DNC_BUSP, "DOUT_CLK_DNC_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_ipp_vclks[] __initdata = {
	VCLK(DOUT_CLK_IPP_BUS, DIV_CLK_IPP_BUS, "DOUT_CLK_IPP_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_IPP_BUSP, DIV_CLK_IPP_BUSP, "DOUT_CLK_IPP_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_itp_vclks[] __initdata = {
	VCLK(DOUT_CLK_ITP_BUS, DIV_CLK_ITP_BUS, "DOUT_CLK_ITP_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_ITP_BUSP, DIV_CLK_ITP_BUSP, "DOUT_CLK_ITP_BUSP", 0, 0, NULL),
};

struct init_vclk exynos9830_mcsc_vclks[] __initdata = {
	VCLK(DOUT_CLK_MCSC_BUS, DIV_CLK_MCSC_BUS, "DOUT_CLK_MCSC_BUS", 0, 0, NULL),
	VCLK(DOUT_CLK_MCSC_BUSP, DIV_CLK_MCSC_BUSP, "DOUT_CLK_MCSC_BUSP", 0, 0, NULL),
};

static struct init_vclk exynos9830_clkout_vclks[] __initdata = {
	VCLK(OSC_NFC, VCLK_CLKOUT1, "OSC_NFC", 0, 0, NULL),
	VCLK(OSC_AUD, VCLK_CLKOUT0, "OSC_AUD", 0, 0, NULL),
};

static __initdata struct of_device_id ext_clk_match[] = {
	{.compatible = "samsung,exynos9830-oscclk", .data = (void *)0},
	{},
};

void exynos9830_vclk_init(void)
{
	/* Common clock init */
}

/* register exynos9830 clocks */
void __init exynos9830_clk_init(struct device_node *np)
{
	void __iomem *reg_base;
	int ret;

	if (np) {
		reg_base = of_iomap(np, 0);
		if (!reg_base)
			panic("%s: failed to map registers\n", __func__);
	} else {
		panic("%s: unable to determine soc\n", __func__);
	}

	ret = cal_if_init(np);
	if (ret)
		panic("%s: unable to initialize cal-if\n", __func__);

	exynos9830_clk_provider = samsung_clk_init(np, reg_base, CLK_NR_CLKS);
	if (!exynos9830_clk_provider)
		panic("%s: unable to allocate context.\n", __func__);

	samsung_register_of_fixed_ext(exynos9830_clk_provider, exynos9830_fixed_rate_ext_clks,
					  ARRAY_SIZE(exynos9830_fixed_rate_ext_clks),
					  ext_clk_match);

	/* register HWACG vclk */
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_apm_hwacg_vclks, ARRAY_SIZE(exynos9830_apm_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_aud_hwacg_vclks, ARRAY_SIZE(exynos9830_aud_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_bus1_hwacg_vclks, ARRAY_SIZE(exynos9830_bus1_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_cmgp_hwacg_vclks, ARRAY_SIZE(exynos9830_cmgp_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_top_hwacg_vclks, ARRAY_SIZE(exynos9830_top_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_core_hwacg_vclks, ARRAY_SIZE(exynos9830_core_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dpu_hwacg_vclks, ARRAY_SIZE(exynos9830_dpu_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dsp0_hwacg_vclks, ARRAY_SIZE(exynos9830_dsp0_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dsp1_hwacg_vclks, ARRAY_SIZE(exynos9830_dsp1_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dsp2_hwacg_vclks, ARRAY_SIZE(exynos9830_dsp2_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dnc_hwacg_vclks, ARRAY_SIZE(exynos9830_dnc_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dns_hwacg_vclks, ARRAY_SIZE(exynos9830_dns_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_hsi0_hwacg_vclks, ARRAY_SIZE(exynos9830_hsi0_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_hsi1_hwacg_vclks, ARRAY_SIZE(exynos9830_hsi1_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_hsi2_hwacg_vclks, ARRAY_SIZE(exynos9830_hsi2_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_g2d_hwacg_vclks, ARRAY_SIZE(exynos9830_g2d_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_g3d_hwacg_vclks, ARRAY_SIZE(exynos9830_g3d_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_ipp_hwacg_vclks, ARRAY_SIZE(exynos9830_ipp_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_itp_hwacg_vclks, ARRAY_SIZE(exynos9830_itp_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_mcsc_hwacg_vclks, ARRAY_SIZE(exynos9830_mcsc_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_csis_hwacg_vclks, ARRAY_SIZE(exynos9830_csis_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_mfc0_hwacg_vclks, ARRAY_SIZE(exynos9830_mfc0_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu00_hwacg_vclks, ARRAY_SIZE(exynos9830_npu00_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu01_hwacg_vclks, ARRAY_SIZE(exynos9830_npu01_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu10_hwacg_vclks, ARRAY_SIZE(exynos9830_npu10_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu11_hwacg_vclks, ARRAY_SIZE(exynos9830_npu11_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_peric0_hwacg_vclks, ARRAY_SIZE(exynos9830_peric0_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_peric1_hwacg_vclks, ARRAY_SIZE(exynos9830_peric1_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_peris_hwacg_vclks, ARRAY_SIZE(exynos9830_peris_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_vra_hwacg_vclks, ARRAY_SIZE(exynos9830_vra_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_vts_hwacg_vclks, ARRAY_SIZE(exynos9830_vts_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_ssp_hwacg_vclks, ARRAY_SIZE(exynos9830_ssp_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_tnr_hwacg_vclks, ARRAY_SIZE(exynos9830_tnr_hwacg_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_mif_hwacg_vclks, ARRAY_SIZE(exynos9830_mif_hwacg_vclks));

	/* register special vclk */
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_apm_vclks, ARRAY_SIZE(exynos9830_apm_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_aud_vclks, ARRAY_SIZE(exynos9830_aud_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_cmgp_vclks, ARRAY_SIZE(exynos9830_cmgp_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_top_vclks, ARRAY_SIZE(exynos9830_top_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_peric0_vclks, ARRAY_SIZE(exynos9830_peric0_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_peric1_vclks, ARRAY_SIZE(exynos9830_peric1_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_vra_vclks, ARRAY_SIZE(exynos9830_vra_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_vts_vclks, ARRAY_SIZE(exynos9830_vts_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_hsi1_vclks, ARRAY_SIZE(exynos9830_hsi1_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_hsi0_vclks, ARRAY_SIZE(exynos9830_hsi0_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu00_vclks, ARRAY_SIZE(exynos9830_npu00_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu01_vclks, ARRAY_SIZE(exynos9830_npu01_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu10_vclks, ARRAY_SIZE(exynos9830_npu10_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_npu11_vclks, ARRAY_SIZE(exynos9830_npu11_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_tnr_vclks, ARRAY_SIZE(exynos9830_tnr_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_csis_vclks, ARRAY_SIZE(exynos9830_csis_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dns_vclks, ARRAY_SIZE(exynos9830_dns_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dsp0_vclks, ARRAY_SIZE(exynos9830_dsp0_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dsp1_vclks, ARRAY_SIZE(exynos9830_dsp1_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dsp2_vclks, ARRAY_SIZE(exynos9830_dsp2_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_dnc_vclks, ARRAY_SIZE(exynos9830_dnc_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_ipp_vclks, ARRAY_SIZE(exynos9830_ipp_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_itp_vclks, ARRAY_SIZE(exynos9830_itp_vclks));
	samsung_register_vclk(exynos9830_clk_provider, exynos9830_mcsc_vclks, ARRAY_SIZE(exynos9830_mcsc_vclks));

	samsung_register_vclk(exynos9830_clk_provider, exynos9830_clkout_vclks, ARRAY_SIZE(exynos9830_clkout_vclks));

	clk_register_fixed_factor(NULL, "pwm-clock", "fin_pll", CLK_SET_RATE_PARENT, 1, 1);

	samsung_clk_of_add_provider(np, exynos9830_clk_provider);

	late_time_init = exynos9830_vclk_init;

	pr_info("EXYNOS9830: Clock setup completed\n");
}

CLK_OF_DECLARE(exynos9830_clk, "samsung,exynos9830-clock", exynos9830_clk_init);
