obj-$(CONFIG_CSIS_V1_2) += is-hw-csi-v1_2.o
obj-$(CONFIG_CSIS_V5_2) += is-hw-csi-v5_2.o
obj-$(CONFIG_CSIS_V5_3) += is-hw-csi-v5_3.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
